/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.GiaTourDTO;
import DTO.TourDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hyung
 */
public class BangTour extends javax.swing.JFrame {

    /**
     * Creates new form DSNV
     */
    int rowTbl;
    public DoanForm doanForm;
    Vector tbCol = new Vector();
    DefaultTableModel tbModel;
    String maTour, tenTour, giaTour;

    public BangTour() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        jBtnXacNhan.setEnabled(false);
        jBtnQuayLai.setEnabled(true);
        initTable();
    }

    public void initTable() {
        tbModel.setRowCount(0);
        tableModel(tbModel);
        jTableTour.setModel(tbModel);
        jBtnXacNhan.setEnabled(false);
        jBtnQuayLai.setEnabled(true);
    }

    public void tableModel(DefaultTableModel model) {
        for (TourDTO tour : DashBoard.tourDTOs) {
            Vector row = new Vector();
            row.add(tour.getMaTour());
            row.add(tour.getTenTour());
            for (GiaTourDTO giaTour : DashBoard.giaTourDTOs) {
                if (giaTour.getMaTour().equals(tour.getMaTour()) && giaTour.getHienHanh() == 1) {
                    row.add(giaTour.getThanhTien());
                    row.add(giaTour.getTgBatDau());
                    row.add(giaTour.getTgKetThuc());
                    break;
                }
            }
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLbManv = new javax.swing.JLabel();
        jTextMaTour = new javax.swing.JTextField();
        jLbHonv = new javax.swing.JLabel();
        jTextTenTour = new javax.swing.JTextField();
        jBtnQuayLai = new javax.swing.JButton();
        jBtnXacNhan = new javax.swing.JButton();
        jLbHonv1 = new javax.swing.JLabel();
        jTextDacDiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTour = new javax.swing.JTable();
        jTextTimKiemTour = new javax.swing.JTextField();
        jBtnTimKiemTour = new javax.swing.JButton();
        jBtnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 245, 252));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setkStartColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(236, 245, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Tour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbManv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv.setText("<html> <body> Mã Tour<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 30));

        jTextMaTour.setEditable(false);
        jTextMaTour.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaTourActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 32, 204, 30));

        jLbHonv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbHonv.setText("<html><body>Tên Tour<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbHonv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 30));

        jTextTenTour.setEditable(false);
        jTextTenTour.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenTourActionPerformed(evt);
            }
        });
        jPanel4.add(jTextTenTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 204, 30));

        jBtnQuayLai.setBackground(new java.awt.Color(136, 193, 184));
        jBtnQuayLai.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back1_16.png"))); // NOI18N
        jBtnQuayLai.setText("Thoát");
        jBtnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuayLaiActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 40));

        jBtnXacNhan.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXacNhan.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ok_16.png"))); // NOI18N
        jBtnXacNhan.setText("Xác nhận");
        jBtnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXacNhanActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 40));

        jLbHonv1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbHonv1.setText("<html><body>Đặc Điểm<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbHonv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        jTextDacDiem.setEditable(false);
        jTextDacDiem.setForeground(new java.awt.Color(51, 51, 51));
        jTextDacDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDacDiemActionPerformed(evt);
            }
        });
        jPanel4.add(jTextDacDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 204, 30));

        jTableTour.setAutoCreateRowSorter(true);
        jTableTour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCol.add("Mă Tour");
        tbCol.add("Tên Tour");
        tbCol.add("Giá Tour");
        tbCol.add("Ngày Bắt Đầu");
        tbCol.add("Ngày Kết Thúc");
        tbModel= new DefaultTableModel(tbCol,5);
        jTableTour.setModel (tbModel);
        jTableTour.setShowGrid(true);
        jTableTour.setFocusable(false);
        jTableTour.setIntercellSpacing(new Dimension(0,0));
        jTableTour.setRowHeight(25);
        jTableTour.getTableHeader().setOpaque(false);
        jTableTour.setFillsViewportHeight(true);
        jTableTour.getTableHeader().setBackground(new Color(232,57,99));
        jTableTour.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableTour.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableTour.setSelectionBackground(new Color(52,152,219));
        jTableTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTour);

        jBtnTimKiemTour.setText("Tìm kiếm");
        jBtnTimKiemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTimKiemTourActionPerformed(evt);
            }
        });

        jBtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefresh.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jTextTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnQuayLaiActionPerformed
    {//GEN-HEADEREND:event_jBtnQuayLaiActionPerformed
        jTextMaTour.setText("");
        jTextTenTour.setText("");
        dispose();
//        jTextTennv.setText("");
//        jTextPban.setText("");
//        jTextCviec.setText("");
    }//GEN-LAST:event_jBtnQuayLaiActionPerformed

    private void jTextTenTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenTourActionPerformed
    {//GEN-HEADEREND:event_jTextTenTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenTourActionPerformed

    private void jTextMaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaTourActionPerformed
    {//GEN-HEADEREND:event_jTextMaTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaTourActionPerformed
    public String ktra() {
        String temp = "";
        if (jTextMaTour.getText().equals("")) {
            temp += "- Vui lòng chọn loại hình!";
        }
        return temp;
    }
    private void jBtnXacNhanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXacNhanActionPerformed
    {//GEN-HEADEREND:event_jBtnXacNhanActionPerformed
//        if (!jBtnXacNhan.isEnabled()) {
//            System.out.println("Disabled");
//        } else {
//            if (ktra().equals("")) {
//                String maLoai = jTextMaLH.getText(), tenLoai = jTextTenLH.getText();
//                if (tourForm != null) {
//                    tourForm.getjTextLoaiHinh().setText(tenLoai);
//                    tourForm.setMaLoai(maLoai);
//                }
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, ktra());
//            }
//        }
        doanForm.setMaTour(maTour);
        doanForm.getjTextTour().setText(tenTour);
        doanForm.getjTextGiaTour().setText(giaTour);
        dispose();
    }//GEN-LAST:event_jBtnXacNhanActionPerformed

    private void jTableTourMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableTourMouseClicked
    {//GEN-HEADEREND:event_jTableTourMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == jTableTour) {
            rowTbl = jTableTour.getSelectedRow();
            System.out.println("rowTb: " + rowTbl);
            if (rowTbl != -1) {
                maTour = (String) jTableTour.getValueAt(rowTbl, 0);
                tenTour = (String) jTableTour.getValueAt(rowTbl, 1);
                giaTour = (String) jTableTour.getValueAt(rowTbl, 2);
                jTextMaTour.setText(maTour);
                jTextTenTour.setText(tenTour);
                for (TourDTO tour : DashBoard.tourDTOs) {
                    if (maTour.equals(tour.getMaTour())) {
                        jTextDacDiem.setText(tour.getDacDiem());
                    }
                }
                jBtnXacNhan.setEnabled(true);
                jBtnQuayLai.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTableTourMouseClicked

    private void jBtnTimKiemTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTimKiemTourActionPerformed
//        // TODO add your handling code here:
//        String manv = jTextTimKiemNV.getText();
//        if (manv.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Má»i nháº­p mÃ£ nhÃ¢n viÃªn cáº§n tÃ¬m");
//        }
//        ArrayList<NhanVienDTO> temp = new ArrayList<NhanVienDTO>(nvBUS.getDsnv().getDsnv());
//        for (int i = 0; i < temp.size(); i++)
//        {
//            if (!(temp.get(i).getManhanvien().equalsIgnoreCase(manv)))
//            {
//                temp.remove(i);
//                i = i - 1;
//            }
//        }
//        searchlistSP(temp);
//        System.out.println("click tim kiem");
    }//GEN-LAST:event_jBtnTimKiemTourActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
        jTextTimKiemTour.setText("");
        initTable();
        jBtnXacNhan.setEnabled(false);
        jBtnRefresh.setEnabled(true);
        jBtnQuayLai.setEnabled(true);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void jTextDacDiemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextDacDiemActionPerformed
    {//GEN-HEADEREND:event_jTextDacDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDacDiemActionPerformed

//    public void searchlistSP(ArrayList<NhanVienDTO> nv)
//    {
//        tbModel.setRowCount(0);
//        outModel(tbModel, nv);
//    }
//    public String getTextFieldContent()
//    {
//        return bccForm.getjTextManv().getText();
//    }
//    public String getTextFieldContentLuong()
//    {
//        return luongForm.getjTextManv().getText();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangTour().setVisible(true);
            }
        });
    }

    public JButton getjBtnQuayLai() {
        return jBtnQuayLai;
    }

    public void setjBtnQuayLai(JButton jBtnQuayLai) {
        this.jBtnQuayLai = jBtnQuayLai;
    }

    public JButton getjBtnRefresh() {
        return jBtnRefresh;
    }

    public void setjBtnRefresh(JButton jBtnRefresh) {
        this.jBtnRefresh = jBtnRefresh;
    }

    public JButton getjBtnTimKiemNV() {
        return jBtnTimKiemTour;
    }

    public void setjBtnTimKiemNV(JButton jBtnTimKiemNV) {
        this.jBtnTimKiemTour = jBtnTimKiemNV;
    }

    public JButton getjBtnXacNhan() {
        return jBtnXacNhan;
    }

    public void setjBtnXacNhan(JButton jBtnXacNhan) {
        this.jBtnXacNhan = jBtnXacNhan;
    }

    public JTable getjTableDsnv() {
        return jTableTour;
    }

    public void setjTableDsnv(JTable jTableDsnv) {
        this.jTableTour = jTableDsnv;
    }

    public JTextField getjTextTimKiemNV() {
        return jTextTimKiemTour;
    }

    public void setjTextTimKiemNV(JTextField jTextTimKiemNV) {
        this.jTextTimKiemTour = jTextTimKiemNV;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnQuayLai;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnTimKiemTour;
    private javax.swing.JButton jBtnXacNhan;
    private javax.swing.JLabel jLbHonv;
    private javax.swing.JLabel jLbHonv1;
    private javax.swing.JLabel jLbManv;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTour;
    private javax.swing.JTextField jTextDacDiem;
    private javax.swing.JTextField jTextMaTour;
    private javax.swing.JTextField jTextTenTour;
    private javax.swing.JTextField jTextTimKiemTour;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
