/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import BUS.CongViecBUS;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import BUS.NhanVienBUS;
//import BUS.NhanVienCongViecBUS;
//import BUS.PhongBanBUS;
//import DTO.NhanVienDTO;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hyung
 */
public class BangGia extends javax.swing.JFrame
{

    /**
     * Creates new form DSNV
     */
//    NhanVienBUS nvBUS = new NhanVienBUS();
//    PhongBanBUS pbBUS = new PhongBanBUS();
//    CongViecBUS cviecBUS = new CongViecBUS();
//    NhanVienCongViecBUS nvcviecBUS = new NhanVienCongViecBUS();
    int rowTbl;
    public TourForm tourForm;
//    public LuongForm luongForm;
//    public thuongphatForm thuongphatForm;
    private boolean thuongphatAc = false;

    public boolean isThuongphatAc()
    {
        return thuongphatAc;
    }

    public void setThuongphatAc(boolean thuongphatAc)
    {
        this.thuongphatAc = thuongphatAc;
    }

    public BangGia()
    {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        jBtnThem.setEnabled(false);
        jBtnSua.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLbManv = new javax.swing.JLabel();
        jTextMaTour = new javax.swing.JTextField();
        jLbHonv = new javax.swing.JLabel();
        jTextMaGia = new javax.swing.JTextField();
        jLbTennv = new javax.swing.JLabel();
        jTextGiaTour = new javax.swing.JTextField();
        jLbPban = new javax.swing.JLabel();
        jLbCviec = new javax.swing.JLabel();
        jBtnSua = new javax.swing.JButton();
        jBtnThem = new javax.swing.JButton();
        jDateKetThuc = new com.toedter.calendar.JDateChooser();
        jDateBatDau = new com.toedter.calendar.JDateChooser();
        jBtnXoa = new javax.swing.JButton();
        jBtnHuy = new javax.swing.JButton();
        jBtnApDung = new javax.swing.JButton();
        jBtnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDsnv = new javax.swing.JTable();
        jTextTimKiemGia = new javax.swing.JTextField();
        jBtnTimKiemNV = new javax.swing.JButton();
        jBtnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 245, 252));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setkStartColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(236, 245, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Giá Tour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbManv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv.setText("<html> <body> Mã Tour <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 32, -1, 30));

        jTextMaTour.setEditable(false);
        jTextMaTour.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaTour.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextMaTourActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 32, 204, 30));

        jLbHonv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbHonv.setText("<html><body>Mã Giá <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbHonv, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 73, 110, 30));

        jTextMaGia.setEditable(false);
        jTextMaGia.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaGia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextMaGiaActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 73, 204, 30));

        jLbTennv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbTennv.setText("<html> <body>Giá Tour <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbTennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 114, -1, 30));

        jTextGiaTour.setEditable(false);
        jTextGiaTour.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(jTextGiaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 114, 204, 30));

        jLbPban.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbPban.setText("<html> <body>Ngày bắt đầu<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbPban, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        jLbCviec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbCviec.setText("<html><body>Ngày kết thúc<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jLbCviec.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLbCviec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jBtnSua.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSua.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSua.setText("Sửa");
        jBtnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSua.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnSuaMouseClicked(evt);
            }
        });
        jBtnSua.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnSuaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, 40));

        jBtnThem.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThem.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThem.setText("Thêm");
        jBtnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnThem.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnThemMouseClicked(evt);
            }
        });
        jBtnThem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnThemActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 40));

        jDateKetThuc.setBackground(new java.awt.Color(214, 217, 223));
        jDateKetThuc.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, 30));

        jDateBatDau.setBackground(new java.awt.Color(214, 217, 223));
        jDateBatDau.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 30));

        jBtnXoa.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoa.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoa.setText("Xóa");
        jBtnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnXoaMouseClicked(evt);
            }
        });
        jBtnXoa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnXoaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 40));

        jBtnHuy.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuy.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuy.setText("Hủy");
        jBtnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnHuy.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnHuyMouseClicked(evt);
            }
        });
        jBtnHuy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnHuyActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 40));

        jBtnApDung.setBackground(new java.awt.Color(136, 193, 184));
        jBtnApDung.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnApDung.setText("Áp Dụng");
        jBtnApDung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnApDung.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnApDungMouseClicked(evt);
            }
        });
        jBtnApDung.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnApDungActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnApDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, 40));

        jBtnThoat.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThoat.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThoat.setText("Thoát");
        jBtnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnThoat.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnThoatMouseClicked(evt);
            }
        });
        jBtnThoat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnThoatActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 100, 40));

        jTableDsnv.setAutoCreateRowSorter(true);
        jTableDsnv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableDsnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        tbCol.add("Mă Giá");
        tbCol.add("Giá Tour");
        tbCol.add("Ngày bắt đầu");
        tbCol.add("Ngày kết thúc");
        tbModel= new DefaultTableModel(tbCol,5);
        jTableDsnv.setModel (tbModel);
        jTableDsnv.setShowGrid(true);
        jTableDsnv.setFocusable(false);
        jTableDsnv.setIntercellSpacing(new Dimension(0,0));
        jTableDsnv.setRowHeight(25);
        jTableDsnv.getTableHeader().setOpaque(false);
        jTableDsnv.setFillsViewportHeight(true);
        jTableDsnv.getTableHeader().setBackground(new Color(232,57,99));
        jTableDsnv.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableDsnv.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableDsnv.setSelectionBackground(new Color(52,152,219));
        //listSP();
        jTableDsnv.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableDsnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDsnv);

        jBtnTimKiemNV.setText("Tìm kiếm");
        jBtnTimKiemNV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnTimKiemNVActionPerformed(evt);
            }
        });

        jBtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefresh.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jTextTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSuaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaActionPerformed
        jTextMaTour.setText("");
        jTextMaGia.setText("");
        jTextGiaTour.setText("");
//        jTextPban.setText("");
//        jTextCviec.setText("");
    }//GEN-LAST:event_jBtnSuaActionPerformed

    private void jBtnSuaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnSuaMouseClicked
    {//GEN-HEADEREND:event_jBtnSuaMouseClicked

    }//GEN-LAST:event_jBtnSuaMouseClicked

    private void jTextMaGiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaGiaActionPerformed
    {//GEN-HEADEREND:event_jTextMaGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaGiaActionPerformed

    private void jTextMaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaTourActionPerformed
    {//GEN-HEADEREND:event_jTextMaTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaTourActionPerformed

    private void jBtnThemMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnThemMouseClicked
    {//GEN-HEADEREND:event_jBtnThemMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnThemMouseClicked
    public String ktra()
    {
        String temp = "";
        if (jTextMaTour.getText().equals(""))
        {
            temp += "- Vui lòng chọn nhân viên!";
        }
        return temp;
    }
    private void jBtnThemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThemActionPerformed
    {//GEN-HEADEREND:event_jBtnThemActionPerformed
//        if (!jBtnXacNhan.isEnabled())
//        {
//            System.out.println("Disabled");
//        } else
//        {
//            if (ktra().equals(""))
//            {
//                String manv = jTextManv.getText();
//                if (bccForm != null)
//                {
//                    bccForm.getjTextManv().setText(manv);
//                }
//                if (luongForm != null)
//                {
//                    luongForm.getjTextManv().setText(manv);
//                }
//                if (thuongphatForm != null && thuongphatAc)
//                {
//                    thuongphatForm.getjTextManv().setText(manv);
//                    thuongphatForm.getjBtnThemTp().setEnabled(true);
//                    thuongphatForm.getjBtnSuaTp().setEnabled(false);
//                    thuongphatForm.getjBtnXoaTp().setEnabled(false);
//                    thuongphatForm.getjBtnHuy().setEnabled(true);
//                    thuongphatAc = false;
//                }
//                setVisible(false);
//                JOptionPane.showMessageDialog(null, "Chọn thành công!");
//            } else
//            {
//                JOptionPane.showMessageDialog(null, ktra());
//            }
//        }
    }//GEN-LAST:event_jBtnThemActionPerformed

    private void jTableDsnvMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableDsnvMouseClicked
    {//GEN-HEADEREND:event_jTableDsnvMouseClicked
        // TODO add your handling code here:
        int rowTbl = jTableDsnv.getSelectedRow();
        jTextMaTour.setText((String) jTableDsnv.getValueAt(rowTbl, 0));
        jTextMaGia.setText((String) jTableDsnv.getValueAt(rowTbl, 1));
        jTextGiaTour.setText((String) jTableDsnv.getValueAt(rowTbl, 2));
//        jTextPban.setText((String) jTableDsnv.getValueAt(rowTbl, 3));
//        jTextCviec.setText((String) jTableDsnv.getValueAt(rowTbl, 4));
        jBtnThem.setEnabled(true);
        jBtnSua.setEnabled(true);
    }//GEN-LAST:event_jTableDsnvMouseClicked

    private void jBtnTimKiemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTimKiemNVActionPerformed
//        // TODO add your handling code here:
//        String manv = jTextTimKiemNV.getText();
//        if (manv.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Má»i nháº­p mÃ£ nhÃ¢n viÃªn cáº§n tÃ¬m");
//        }
//        ArrayList<NhanVienDTO> temp = new ArrayList<NhanVienDTO>(nvBUS.getDsnv().getDsnv());
//        for (int i = 0; i < temp.size(); i++)
//        {
//            if (!(temp.get(i).getManhanvien().equalsIgnoreCase(manv)))
//            {
//                temp.remove(i);
//                i = i - 1;
//            }
//        }
//        searchlistSP(temp);
//        System.out.println("click tim kiem");
    }//GEN-LAST:event_jBtnTimKiemNVActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
//        jTextTimKiemNV.setText("");
//        listSP();
//        jBtnXacNhan.setEnabled(false);
//        jBtnRefresh.setEnabled(true);
//        jBtnQuayLai.setEnabled(false);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnXoaMouseClicked
    {//GEN-HEADEREND:event_jBtnXoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaMouseClicked

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnHuyMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnHuyMouseClicked
    {//GEN-HEADEREND:event_jBtnHuyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuyMouseClicked

    private void jBtnHuyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuyActionPerformed

    private void jBtnApDungMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnApDungMouseClicked
    {//GEN-HEADEREND:event_jBtnApDungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApDungMouseClicked

    private void jBtnApDungActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnApDungActionPerformed
    {//GEN-HEADEREND:event_jBtnApDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApDungActionPerformed

    private void jBtnThoatMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnThoatMouseClicked
    {//GEN-HEADEREND:event_jBtnThoatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThoatMouseClicked

    private void jBtnThoatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThoatActionPerformed
    {//GEN-HEADEREND:event_jBtnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThoatActionPerformed

//    public void outModel(DefaultTableModel model, ArrayList<NhanVienDTO> nv) // Xuất ra Table từ ArrayList
//    {
//        Vector data;
//        model.setRowCount(0);
//        for (NhanVienDTO nvDto : nv)
//        {
//            data = new Vector();
//            data.add(nvDto.getManhanvien());
//            data.add(nvDto.getHonhanvien());
//            data.add(nvDto.getTennhanvien());
//            for (int i = 0; i < pbBUS.getDspb().getDspb().size(); ++i)
//            {
//                if (nvDto.getMaphongban().equals(pbBUS.getDspb().getDspb().get(i).getMaphongban()))
//                {
//                    data.add(pbBUS.getDspb().getDspb().get(i).getTenphongban());
//                }
//            }
//            for (int i = 0; i < nvcviecBUS.getDsnvcviec().getDsnvcviec().size(); ++i)
//            {
//                if (nvDto.getManhanvien().equals(nvcviecBUS.getDsnvcviec().getDsnvcviec().get(i).getManhanvien()))
//                {
//                    for (int j = 0; j < cviecBUS.getDscviec().getDscviec().size(); ++j)
//                    {
//                        if (nvcviecBUS.getDsnvcviec().getDsnvcviec().get(i).getMacongviec().equals(cviecBUS.getDscviec().getDscviec().get(j).getMacongviec()))
//                        {
//                            data.add(cviecBUS.getDscviec().getDscviec().get(j).getTencongviec());
//                        }
//                    }
//                }
//            }
//            model.addRow(data);
//        }
//        //jTableDsnv.setModel(model);
//    }
//    public void listSP() // Chép ArrayList lên table
//    {
////        if(nvBUS.getDsnv ().getDsnv ()== null)nvBUS.listNV();
//        ArrayList<NhanVienDTO> nv = nvBUS.getDsnv().getDsnv();
//        tbModel.setRowCount(0);
//        outModel(tbModel, nv);
//    }
//
//    public void searchlistSP(ArrayList<NhanVienDTO> nv)
//    {
//        tbModel.setRowCount(0);
//        outModel(tbModel, nv);
//    }
//
//    public String getTextFieldContent()
//    {
//        return bccForm.getjTextManv().getText();
//    }
//
//    public String getTextFieldContentLuong()
//    {
//        return luongForm.getjTextManv().getText();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BangGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BangGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BangGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BangGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BangGia().setVisible(true);
            }
        });
    }

    public JButton getjBtnQuayLai()
    {
        return jBtnSua;
    }

    public void setjBtnQuayLai(JButton jBtnQuayLai)
    {
        this.jBtnSua = jBtnQuayLai;
    }

    public JButton getjBtnRefresh()
    {
        return jBtnRefresh;
    }

    public void setjBtnRefresh(JButton jBtnRefresh)
    {
        this.jBtnRefresh = jBtnRefresh;
    }

    public JButton getjBtnTimKiemNV()
    {
        return jBtnTimKiemNV;
    }

    public void setjBtnTimKiemNV(JButton jBtnTimKiemNV)
    {
        this.jBtnTimKiemNV = jBtnTimKiemNV;
    }

    public JButton getjBtnXacNhan()
    {
        return jBtnThem;
    }

    public void setjBtnXacNhan(JButton jBtnXacNhan)
    {
        this.jBtnThem = jBtnXacNhan;
    }

    public JTable getjTableDsnv()
    {
        return jTableDsnv;
    }

    public void setjTableDsnv(JTable jTableDsnv)
    {
        this.jTableDsnv = jTableDsnv;
    }

//    public JTextField getjTextTjTextTimKiemGia {
//        return jTextTimKiemNV;
//    }
//
//    public void setjTextTimKiemNV(JTextField jTejTextTimKiemGia   {
//        this.jTextTimKiemNV = jTextTimKiemNV;
//    }

    Vector tbCol = new Vector();
    DefaultTableModel tbModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApDung;
    private javax.swing.JButton jBtnHuy;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnSua;
    private javax.swing.JButton jBtnThem;
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JButton jBtnTimKiemNV;
    private javax.swing.JButton jBtnXoa;
    private com.toedter.calendar.JDateChooser jDateBatDau;
    private com.toedter.calendar.JDateChooser jDateKetThuc;
    private javax.swing.JLabel jLbCviec;
    private javax.swing.JLabel jLbHonv;
    private javax.swing.JLabel jLbManv;
    private javax.swing.JLabel jLbPban;
    private javax.swing.JLabel jLbTennv;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDsnv;
    private javax.swing.JTextField jTextGiaTour;
    private javax.swing.JTextField jTextMaGia;
    private javax.swing.JTextField jTextMaTour;
    private javax.swing.JTextField jTextTimKiemGia;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
