/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import BUS.CongViecBUS;
import BUS.GiaTourBUS;
import DTO.GiaTourDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import BUS.NhanVienBUS;
//import BUS.NhanVienCongViecBUS;
//import BUS.PhongBanBUS;
//import DTO.NhanVienDTO;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hyung
 */
public class BangChiPhi extends javax.swing.JFrame
{

    /**
     * Creates new form DSNV
     */
    int rowTbl;
    public TourForm tourForm;
    DoanForm doanForm;
    public GiaTourBUS giaTourBUS;
    private boolean thuongphatAc = false;
    Vector tbCol = new Vector();
    DefaultTableModel tbModel;
    String maTour, maGiaHH;
    int hienHanh;

    public BangChiPhi()
    {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    public BangChiPhi(String maTour, String maGiaHH)
    {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.maTour = maTour;
        this.maGiaHH = maGiaHH;
        System.out.println("maTourCon: " + this.maTour);
        System.out.println("maGiaCon: " + this.maGiaHH);
        initTable();
        jTableChiPhi.setEditingColumn(5);
        jTextMaDoan.setText(this.maTour);
        jTextTenDoan.setText(this.maGiaHH);
        jBtnCapPhatMaChiPhi.setEnabled(true);
        jBtnThem.setEnabled(false);
        jBtnSua.setEnabled(false);
        jBtnXoa.setEnabled(false);
        jBtnHuy.setEnabled(false);
//        jBtnXacNhan.setEnabled(false);
        jBtnThoat.setEnabled(true);
    }

    public void reloadData()
    {
        giaTourBUS = new GiaTourBUS();
    }

    public void initTable()
    {
        reloadData();
        tbModel.setRowCount(0);
        tableModel(tbModel);
        jTableChiPhi.setModel(tbModel);
    }

    public void tableModel(DefaultTableModel model)
    {
        for (GiaTourDTO giaTour : giaTourBUS.getGiaTourDTOs())
        {
            if (giaTour.getMaTour().equals(this.maTour))
            {
                Vector row = new Vector();
                row.add(giaTour.getMaGia());
                row.add(giaTour.getThanhTien());
                row.add(giaTour.getTgBatDau());
                row.add(giaTour.getTgKetThuc());
                if (giaTour.getHienHanh() == 1)
                {
                    row.add("X");
                } else
                {
                    row.add("");
                }
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLbMaGia = new javax.swing.JLabel();
        jTextMaChiPhi = new javax.swing.JTextField();
        jLbGiaTour = new javax.swing.JLabel();
        jBtnSua = new javax.swing.JButton();
        jBtnThem = new javax.swing.JButton();
        jBtnXoa = new javax.swing.JButton();
        jBtnHuy = new javax.swing.JButton();
        jBtnThoat = new javax.swing.JButton();
        jLbMaTour = new javax.swing.JLabel();
        jTextMaDoan = new javax.swing.JTextField();
        jLbMaGiaNow = new javax.swing.JLabel();
        jTextTenDoan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnCapPhatMaChiPhi = new javax.swing.JButton();
        jLbGiaTour1 = new javax.swing.JLabel();
        jTextLoaiChiPhi1 = new javax.swing.JTextField();
        jCbGioiTinh = new javax.swing.JComboBox<>();
        jTextGhiChu = new javax.swing.JTextField();
        jLbGiaTour2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChiPhi = new javax.swing.JTable();
        jTextTimKiemGia = new javax.swing.JTextField();
        jBtnTimKiemGia = new javax.swing.JButton();
        jBtnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 245, 252));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setkStartColor(new java.awt.Color(236, 245, 252));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(236, 245, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Phí Tour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbMaGia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbMaGia.setText("<html><body>Mã Chi Phí <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbMaGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jTextMaChiPhi.setEditable(false);
        jTextMaChiPhi.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaChiPhi.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaChiPhiActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 30));

        jLbGiaTour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbGiaTour.setText("<html> <body>Loai Chi Phí <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbGiaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jBtnSua.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSua.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSua.setText("Sửa");
        jBtnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, 40));

        jBtnThem.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThem.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThem.setText("Thêm");
        jBtnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 40));

        jBtnXoa.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoa.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoa.setText("Xóa");
        jBtnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 100, 40));

        jBtnHuy.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuy.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuy.setText("Hủy");
        jBtnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 40));

        jBtnThoat.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThoat.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThoat.setText("Thoát");
        jBtnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThoatActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 100, 40));

        jLbMaTour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbMaTour.setText("<html> <body> Mã Đoàn</body> </html>");
        jPanel4.add(jLbMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jTextMaDoan.setEditable(false);
        jTextMaDoan.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaDoan.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaDoanActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 30));

        jLbMaGiaNow.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbMaGiaNow.setText("<html><body>Tên Đoàn</body> </html>");
        jPanel4.add(jLbMaGiaNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 50));

        jTextTenDoan.setEditable(false);
        jTextTenDoan.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenDoan.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenDoanActionPerformed(evt);
            }
        });
        jPanel4.add(jTextTenDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 10));

        jBtnCapPhatMaChiPhi.setBackground(new java.awt.Color(81, 113, 131));
        jBtnCapPhatMaChiPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_32.png"))); // NOI18N
        jBtnCapPhatMaChiPhi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCapPhatMaChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapPhatMaChiPhiActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnCapPhatMaChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 30, 30));

        jLbGiaTour1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbGiaTour1.setText("<html> <body>Ghi Chú <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbGiaTour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jTextLoaiChiPhi1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(jTextLoaiChiPhi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 30));

        jCbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "L4..." }));
        jCbGioiTinh.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel4.add(jCbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 172, 160, 30));

        jTextGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGhiChuActionPerformed(evt);
            }
        });
        jPanel4.add(jTextGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 160, 70));

        jLbGiaTour2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbGiaTour2.setText("<html> <body>Thành Tiền <span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbGiaTour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jTableChiPhi.setAutoCreateRowSorter(true);
        jTableChiPhi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableChiPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCol.add("Mă Chi Phí");
        tbCol.add("Loại Chi Phí");
        tbCol.add("Thành Tiền");
        tbModel= new DefaultTableModel(tbCol,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableChiPhi.setModel (tbModel);
        jTableChiPhi.setShowGrid(true);
        jTableChiPhi.setFocusable(false);
        jTableChiPhi.setIntercellSpacing(new Dimension(0,0));
        jTableChiPhi.setRowHeight(25);
        jTableChiPhi.getTableHeader().setOpaque(false);
        jTableChiPhi.setFillsViewportHeight(true);
        jTableChiPhi.getTableHeader().setBackground(new Color(232,57,99));
        jTableChiPhi.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableChiPhi.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableChiPhi.setSelectionBackground(new Color(52,152,219));
        //listSP();
        jTableChiPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChiPhiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableChiPhi);

        jBtnTimKiemGia.setText("Tìm kiếm");
        jBtnTimKiemGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTimKiemGiaActionPerformed(evt);
            }
        });

        jBtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefresh.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jTextTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTimKiemGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSuaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaActionPerformed
//        String maGia = (String) jTextMaChiPhi.getText(),
//                giaTour = (String) jTextLoaiChiPhi.getText(),
//                ngayBD = (String) ((JTextField) jDateBatDau.getDateEditor().getUiComponent()).getText(),
//                ngayKT = (String) ((JTextField) jDateKetThuc.getDateEditor().getUiComponent()).getText();
//        if (giaTourBUS.suaGiaTour(tourForm.getMaTour(), maGia, giaTour, ngayBD, ngayKT, hienHanh))
//        {
//            tourForm.getjTextGiaTour().setText(giaTour);
//            tourForm.getjDateNgayBD().setCalendar(jDateBatDau.getCalendar());
//            tourForm.getjDateNgayKT().setCalendar(jDateKetThuc.getCalendar());
//            tourForm.getTbModelTour().setValueAt(giaTour, tourForm.getRowTour(), 3);
//            tourForm.getTbModelTour().setValueAt(ngayBD, tourForm.getRowTour(), 4);
//            tourForm.getTbModelTour().setValueAt(ngayKT, tourForm.getRowTour(), 5);
//            initTable();
//            JOptionPane.showMessageDialog(this, "Sửa Giá Tour thành công!");
//        } else
//        {
//            JOptionPane.showMessageDialog(this, "Sửa Giá Tour thất bại!");
//        }
//        jTextMaChiPhi.setText("");
//        jTextLoaiChiPhi.setText("");
//        jDateBatDau.setCalendar(null);
//        jDateKetThuc.setCalendar(null);
//        jBtnCapPhatMaChiPhi.setEnabled(true);
//        jBtnThem.setEnabled(false);
//        jBtnSua.setEnabled(false);
//        jBtnXoa.setEnabled(false);
//        jBtnHuy.setEnabled(false);
//        jBtnXacNhan.setEnabled(false);
//        jBtnThoat.setEnabled(true);
//        jTextPban.setText("");
//        jTextCviec.setText("");
    }//GEN-LAST:event_jBtnSuaActionPerformed

    private void jTextMaChiPhiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaChiPhiActionPerformed
    {//GEN-HEADEREND:event_jTextMaChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaChiPhiActionPerformed

    private void jTextMaDoanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaDoanActionPerformed
    {//GEN-HEADEREND:event_jTextMaDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaDoanActionPerformed
    public String ktra()
    {
        String temp = "";
        if (jTextMaDoan.getText().equals(""))
        {
            temp += "- Vui lòng chọn giá tour!";
        }
        return temp;
    }
    private void jBtnThemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThemActionPerformed
    {//GEN-HEADEREND:event_jBtnThemActionPerformed
//        String maGia = (String) jTextMaChiPhi.getText(),
//                maTour = (String) jTextMaDoan.getText(),
//                giaTour = (String) jTextLoaiChiPhi.getText(),
//                ngayBD = (String) ((JTextField) jDateBatDau.getDateEditor().getUiComponent()).getText(),
//                ngayKT = (String) ((JTextField) jDateKetThuc.getDateEditor().getUiComponent()).getText();
//        if (giaTourBUS.themGiaTour(maGia, maTour, giaTour, ngayBD, ngayKT))
//        {
//            initTable();
//            JOptionPane.showMessageDialog(this, "Thêm Giá Tour thành công!");
//        } else
//        {
//            JOptionPane.showMessageDialog(this, "Thêm Giá Tour thất bại!");
//        }
//        jTextMaChiPhi.setText("");
//        jTextLoaiChiPhi.setText("");
//        jDateBatDau.setCalendar(null);
//        jDateKetThuc.setCalendar(null);
//        jBtnCapPhatMaChiPhi.setEnabled(true);
//        jBtnThem.setEnabled(false);
//        jBtnSua.setEnabled(false);
//        jBtnXoa.setEnabled(false);
//        jBtnHuy.setEnabled(false);
//        jBtnXacNhan.setEnabled(false);
//        jBtnThoat.setEnabled(true);
//        if (!jBtnXacNhan.isEnabled())
//        {
//            System.out.println("Disabled");
//        } else
//        {
//            if (ktra().equals(""))
//            {
//                String manv = jTextManv.getText();
//                if (bccForm != null)
//                {
//                    bccForm.getjTextManv().setText(manv);
//                }
//                if (luongForm != null)
//                {
//                    luongForm.getjTextManv().setText(manv);
//                }
//                if (thuongphatForm != null && thuongphatAc)
//                {
//                    thuongphatForm.getjTextManv().setText(manv);
//                    thuongphatForm.getjBtnThemTp().setEnabled(true);
//                    thuongphatForm.getjBtnSuaTp().setEnabled(false);
//                    thuongphatForm.getjBtnXoaTp().setEnabled(false);
//                    thuongphatForm.getjBtnHuy().setEnabled(true);
//                    thuongphatAc = false;
//                }
//                setVisible(false);
//                JOptionPane.showMessageDialog(null, "Chọn thành công!");
//            } else
//            {
//                JOptionPane.showMessageDialog(null, ktra());
//            }
//        }
    }//GEN-LAST:event_jBtnThemActionPerformed

    private void jTableChiPhiMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableChiPhiMouseClicked
    {//GEN-HEADEREND:event_jTableChiPhiMouseClicked
        // TODO add your handling code here:
//        if (evt.getSource() == jTableGiaTour)
//        {
//            rowTbl = jTableGiaTour.getSelectedRow();
//            if (rowTbl != -1)
//            {
//                jTextMaChiPhi.setText((String) jTableGiaTour.getValueAt(rowTbl, 0));
//                jTextLoaiChiPhi.setText((String) jTableGiaTour.getValueAt(rowTbl, 1));
//                try
//                {
//                    Date dateBD = new SimpleDateFormat("yyyy-MM-dd").parse(jTableGiaTour.getModel().getValueAt(rowTbl, 2).toString());
//                    jDateBatDau.setDate(dateBD);
//                } catch (Exception e)
//                {
//                    JOptionPane.showMessageDialog(BangChiPhi.this, e);
//                    System.out.println("- Load sai ngày bắt đầu!");
//                }
//                try
//                {
//                    Date dateBD = new SimpleDateFormat("yyyy-MM-dd").parse(jTableGiaTour.getModel().getValueAt(rowTbl, 3).toString());
//                    jDateKetThuc.setDate(dateBD);
//                } catch (Exception e)
//                {
//                    JOptionPane.showMessageDialog(BangChiPhi.this, e);
//                    System.out.println("- Load sai ngày kết thúc!");
//                }
//                if (jTableGiaTour.getValueAt(rowTbl, 4).equals("X"))
//                {
//                    System.out.println("Hiện hành");
//                    hienHanh = 1;
//                    jBtnXoa.setEnabled(false);
//                    jBtnXacNhan.setEnabled(false);
//                } else
//                {
//                    hienHanh = 0;
//                    jBtnXoa.setEnabled(true);
//                    jBtnXacNhan.setEnabled(true);
//                }
//                jBtnCapPhatMaChiPhi.setEnabled(false);
//                jBtnThem.setEnabled(false);
//                jBtnSua.setEnabled(true);
//                jBtnHuy.setEnabled(true);
//                jBtnThoat.setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_jTableChiPhiMouseClicked

    private void jBtnTimKiemGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTimKiemGiaActionPerformed
//        // TODO add your handling code here:
//        String manv = jTextTimKiemNV.getText();
//        if (manv.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Má»i nháº­p mÃ£ nhÃ¢n viÃªn cáº§n tÃ¬m");
//        }
//        ArrayList<NhanVienDTO> temp = new ArrayList<NhanVienDTO>(nvBUS.getDsnv().getDsnv());
//        for (int i = 0; i < temp.size(); i++)
//        {
//            if (!(temp.get(i).getManhanvien().equalsIgnoreCase(manv)))
//            {
//                temp.remove(i);
//                i = i - 1;
//            }
//        }
//        searchlistSP(temp);
//        System.out.println("click tim kiem");
    }//GEN-LAST:event_jBtnTimKiemGiaActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
//        jTextTimKiemNV.setText("");
//        listSP();
//        jBtnXacNhan.setEnabled(false);
//        jBtnRefresh.setEnabled(true);
//        jBtnQuayLai.setEnabled(false);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaActionPerformed
//        // TODO add your handling code here:
//        String maGia = (String) jTextMaChiPhi.getText(),
//                giaTour = (String) jTextLoaiChiPhi.getText(),
//                ngayBD = (String) ((JTextField) jDateBatDau.getDateEditor().getUiComponent()).getText(),
//                ngayKT = (String) ((JTextField) jDateKetThuc.getDateEditor().getUiComponent()).getText();
//        if (giaTourBUS.xoaGiaTour(tourForm.getMaTour(), maGia, giaTour, ngayBD, ngayKT, hienHanh))
//        {
//            initTable();
//            JOptionPane.showMessageDialog(this, "Xóa Giá Tour thành công!");
//        } else
//        {
//            JOptionPane.showMessageDialog(this, "Xóa Giá Tour thất bại!");
//        }
//        jTextMaChiPhi.setText("");
//        jTextLoaiChiPhi.setText("");
//        jDateBatDau.setCalendar(null);
//        jDateKetThuc.setCalendar(null);
//        jBtnCapPhatMaChiPhi.setEnabled(true);
//        jBtnThem.setEnabled(false);
//        jBtnSua.setEnabled(false);
//        jBtnXoa.setEnabled(false);
//        jBtnHuy.setEnabled(false);
//        jBtnXacNhan.setEnabled(false);
//        jBtnThoat.setEnabled(true);
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnHuyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyActionPerformed
//        // TODO add your handling code here:
//        jTextMaChiPhi.setText("");
//        jTextLoaiChiPhi.setText("");
//        jDateBatDau.setCalendar(null);
//        jDateKetThuc.setCalendar(null);
//        jBtnCapPhatMaChiPhi.setEnabled(true);
//        jBtnThem.setEnabled(false);
//        jBtnSua.setEnabled(false);
//        jBtnXoa.setEnabled(false);
//        jBtnHuy.setEnabled(false);
//        jBtnXacNhan.setEnabled(false);
//        jBtnThoat.setEnabled(true);
    }//GEN-LAST:event_jBtnHuyActionPerformed

    private void jBtnThoatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThoatActionPerformed
    {//GEN-HEADEREND:event_jBtnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnThoatActionPerformed

    private void jTextTenDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTenDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenDoanActionPerformed

    private void jBtnCapPhatMaChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCapPhatMaChiPhiActionPerformed
        // TODO add your handling code here:
//        reloadData();
//        String init = null;
//        init = giaTourBUS.CapPhat(init);
//        jTextMaChiPhi.setText(init);
//        jBtnCapPhatMaChiPhi.setEnabled(false);
//        jBtnThem.setEnabled(true);
//        jBtnSua.setEnabled(false);
//        jBtnXoa.setEnabled(false);
//        jBtnHuy.setEnabled(true);
//        jBtnXacNhan.setEnabled(false);
//        jBtnThoat.setEnabled(true);
    }//GEN-LAST:event_jBtnCapPhatMaChiPhiActionPerformed

    private void jTextGhiChuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextGhiChuActionPerformed
    {//GEN-HEADEREND:event_jTextGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGhiChuActionPerformed

//    public void searchlistSP(ArrayList<NhanVienDTO> nv)
//    {
//        tbModel.setRowCount(0);
//        outModel(tbModel, nv);
//    }
//
//    public String getTextFieldContent()
//    {
//        return bccForm.getjTextManv().getText();
//    }
//
//    public String getTextFieldContentLuong()
//    {
//        return luongForm.getjTextManv().getText();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BangChiPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BangChiPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BangChiPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BangChiPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BangChiPhi().setVisible(true);
            }
        });
    }

    public JButton getjBtnQuayLai()
    {
        return jBtnSua;
    }

    public void setjBtnQuayLai(JButton jBtnQuayLai)
    {
        this.jBtnSua = jBtnQuayLai;
    }

    public JButton getjBtnXacNhan()
    {
        return jBtnThem;
    }

    public void setjBtnXacNhan(JButton jBtnXacNhan)
    {
        this.jBtnThem = jBtnXacNhan;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapPhatMaChiPhi;
    private javax.swing.JButton jBtnHuy;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnSua;
    private javax.swing.JButton jBtnThem;
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JButton jBtnTimKiemGia;
    private javax.swing.JButton jBtnXoa;
    private javax.swing.JComboBox<String> jCbGioiTinh;
    private javax.swing.JLabel jLbGiaTour;
    private javax.swing.JLabel jLbGiaTour1;
    private javax.swing.JLabel jLbGiaTour2;
    private javax.swing.JLabel jLbMaGia;
    private javax.swing.JLabel jLbMaGiaNow;
    private javax.swing.JLabel jLbMaTour;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableChiPhi;
    private javax.swing.JTextField jTextGhiChu;
    private javax.swing.JTextField jTextLoaiChiPhi1;
    private javax.swing.JTextField jTextMaChiPhi;
    private javax.swing.JTextField jTextMaDoan;
    private javax.swing.JTextField jTextTenDoan;
    private javax.swing.JTextField jTextTimKiemGia;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
