/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import DTO.AccountDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
//import ui.nhanvienForm;

/**
 *
 * @author Hyung
 */
public class DashBoard extends javax.swing.JFrame
{

    private boolean check = true;
    private TourForm tourForm;
    private DiadiemForm diadiemForm;
    private NhanVienForm nhanvienForm;
    private KhachHangForm khachhangForm;
    private DoanForm doanForm;
//    private phongbanForm pb;
//    private duanForm da;
//    private hopdongForm hd;
//    private BccForm bcc;
//    private phucapForm phucap;
//    private LuongForm luong;
//    private AccountDTO account;
//    private thuongphatForm thuongphat;
    static int loadagain = 0;
    private int flagAcc;
    private String mapb;

    /**
     * Creates new form DashBoard
     */
//    public DashBoard (AccountDTO account)
//    {
//        nv = new nhanvienForm ();
//        pb = new phongbanForm ();
//        da = new duanForm ();
//        hd = new hopdongForm ();
//        bcc = new BccForm ();
//        phucap = new phucapForm ();
//        luong = new LuongForm ();
//        thuongphat = new thuongphatForm();
//        initComponents ();
//        if(account.getQuyen().equals("admin")){
//            flagAcc = 0;
//        }
//        if(account.getQuyen().equals("quanly") || account.getQuyen().equals("Quản lý")){
//            flagAcc = 1;
//        }
//        if(account.getQuyen().equals("nhanvien") || account.getQuyen().equals("Nhân Viên")){
//            flagAcc = 2;
//        }
//        setLocationRelativeTo (null);
//        setDefaultCloseOperation (DashBoard.DISPOSE_ON_CLOSE);
//    }
    public DashBoard()
    {
        tourForm = new TourForm();
        diadiemForm = new DiadiemForm();
        nhanvienForm = new NhanVienForm();
        khachhangForm = new KhachHangForm();
        doanForm = new DoanForm();
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DashBoard.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabelMini = new javax.swing.JLabel();
        jLabelClosed = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehideMenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        btnHidemenu = new javax.swing.JLabel();
        settingLogout = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tourPanel = new javax.swing.JPanel();
        tourLabel = new javax.swing.JLabel();
        diadiemPanel = new javax.swing.JPanel();
        diadiemLabel = new javax.swing.JLabel();
        hopdongPanel = new javax.swing.JPanel();
        hopdongLabel = new javax.swing.JLabel();
        khachPanel = new javax.swing.JPanel();
        khachLabel = new javax.swing.JLabel();
        nhanvienPanel = new javax.swing.JPanel();
        nhanvienLabel = new javax.swing.JLabel();
        thuongphatPanel = new javax.swing.JPanel();
        thuongphatLabel = new javax.swing.JLabel();
        luongPanel = new javax.swing.JPanel();
        luongLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelTour = new javax.swing.JPanel();
        jPanelDiaDiem = new javax.swing.JPanel();
        jPanelKhach = new javax.swing.JPanel();
        jPanelNhanvien = new javax.swing.JPanel();
        jPanelDoan = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(212, 236, 189));
        kGradientPanel1.setkStartColor(new java.awt.Color(66, 98, 124));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkGradientFocus(1000);
        kGradientPanel2.setkStartColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkTransparentControls(false);
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_minimize_window_48.png"))); // NOI18N
        jLabelMini.setToolTipText("Minimize");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });
        jLabelMini.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelMiniPropertyChange(evt);
            }
        });
        kGradientPanel2.add(jLabelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 0, 40, 50));

        jLabelClosed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_48.png"))); // NOI18N
        jLabelClosed.setToolTipText("Close");
        jLabelClosed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClosed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClosedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClosedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClosedMouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabelClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 0, 40, 50));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(167, 193, 169));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tour-guide-40.png"))); // NOI18N
        jLabel4.setToolTipText("");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 242, 249));
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 170, 50));
        jLabel5.getText ();

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(167, 193, 169));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_waving_hand_emoji_32.png"))); // NOI18N
        jLabel6.setText("Xin chào");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 150, 50));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 242, 249));
        jLabel8.setText("<html> <span>QUẢN LÝ TOUR DU LỊCH<span> </html> ");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 50));
        jLabel5.getText ();

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(81, 113, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 650));

        menuIcon.setBackground(new java.awt.Color(66, 98, 124));
        menuIcon.setMinimumSize(new java.awt.Dimension(100, 5));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 650));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehideMenu.setBackground(new java.awt.Color(66, 98, 124));
        linehideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehideMenuLayout = new javax.swing.GroupLayout(linehideMenu);
        linehideMenu.setLayout(linehideMenuLayout);
        linehideMenuLayout.setHorizontalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehideMenuLayout.setVerticalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(linehideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hidemenu.setBackground(new java.awt.Color(66, 98, 124));
        hidemenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hidemenu.setLayout(new java.awt.BorderLayout());

        btnHidemenu.setBackground(new java.awt.Color(66, 98, 124));
        btnHidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_menu_32.png"))); // NOI18N
        btnHidemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHidemenuMouseExited(evt);
            }
        });
        hidemenu.add(btnHidemenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, -1));

        settingLogout.setBackground(new java.awt.Color(66, 98, 124));
        settingLogout.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout settingLogoutLayout = new javax.swing.GroupLayout(settingLogout);
        settingLogout.setLayout(settingLogoutLayout);
        settingLogoutLayout.setHorizontalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        settingLogoutLayout.setVerticalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(settingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        logout.setBackground(new java.awt.Color(66, 98, 124));
        logout.setPreferredSize(new java.awt.Dimension(50, 50));
        logout.setLayout(new java.awt.BorderLayout());

        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_32.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        logout.add(btnLogout, java.awt.BorderLayout.CENTER);

        menuIcon.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        jPanel3.setBackground(new java.awt.Color(81, 113, 131));

        jPanel5.setBackground(new java.awt.Color(81, 113, 131));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 245, 253));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tourPanel.setBackground(new java.awt.Color(81, 113, 131));
        tourPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        tourLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        tourLabel.setForeground(new java.awt.Color(208, 245, 253));
        tourLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-wine-tour-32.png"))); // NOI18N
        tourLabel.setText("TOUR");
        tourLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        tourLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tourLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tourLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tourLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tourLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tourPanelLayout = new javax.swing.GroupLayout(tourPanel);
        tourPanel.setLayout(tourPanelLayout);
        tourPanelLayout.setHorizontalGroup(
            tourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tourLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tourPanelLayout.setVerticalGroup(
            tourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        diadiemPanel.setBackground(new java.awt.Color(81, 113, 131));
        diadiemPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        diadiemLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        diadiemLabel.setForeground(new java.awt.Color(208, 245, 253));
        diadiemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-place-32.png"))); // NOI18N
        diadiemLabel.setText("ĐỊA ĐIỂM");
        diadiemLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        diadiemLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diadiemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diadiemLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                diadiemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                diadiemLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout diadiemPanelLayout = new javax.swing.GroupLayout(diadiemPanel);
        diadiemPanel.setLayout(diadiemPanelLayout);
        diadiemPanelLayout.setHorizontalGroup(
            diadiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diadiemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diadiemPanelLayout.setVerticalGroup(
            diadiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diadiemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        hopdongPanel.setBackground(new java.awt.Color(81, 113, 131));
        hopdongPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        hopdongLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        hopdongLabel.setForeground(new java.awt.Color(208, 245, 253));
        hopdongLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tourist-32.png"))); // NOI18N
        hopdongLabel.setText("ĐOÀN THAM QUAN");
        hopdongLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        hopdongLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hopdongLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hopdongLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hopdongLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hopdongLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hopdongPanelLayout = new javax.swing.GroupLayout(hopdongPanel);
        hopdongPanel.setLayout(hopdongPanelLayout);
        hopdongPanelLayout.setHorizontalGroup(
            hopdongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hopdongLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hopdongPanelLayout.setVerticalGroup(
            hopdongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hopdongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        khachPanel.setBackground(new java.awt.Color(81, 113, 131));
        khachPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khachPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        khachLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        khachLabel.setForeground(new java.awt.Color(208, 245, 253));
        khachLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-32.png"))); // NOI18N
        khachLabel.setText("KHÁCH HÀNG");
        khachLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        khachLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khachLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                khachLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                khachLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout khachPanelLayout = new javax.swing.GroupLayout(khachPanel);
        khachPanel.setLayout(khachPanelLayout);
        khachPanelLayout.setHorizontalGroup(
            khachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khachLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        khachPanelLayout.setVerticalGroup(
            khachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khachLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        nhanvienPanel.setBackground(new java.awt.Color(81, 113, 131));
        nhanvienPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        nhanvienLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        nhanvienLabel.setForeground(new java.awt.Color(208, 245, 253));
        nhanvienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-staff-32.png"))); // NOI18N
        nhanvienLabel.setText("NHÂN VIÊN");
        nhanvienLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nhanvienLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nhanvienLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanvienLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhanvienLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhanvienLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nhanvienPanelLayout = new javax.swing.GroupLayout(nhanvienPanel);
        nhanvienPanel.setLayout(nhanvienPanelLayout);
        nhanvienPanelLayout.setHorizontalGroup(
            nhanvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhanvienLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nhanvienPanelLayout.setVerticalGroup(
            nhanvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhanvienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        thuongphatPanel.setBackground(new java.awt.Color(81, 113, 131));
        thuongphatPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        thuongphatLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        thuongphatLabel.setForeground(new java.awt.Color(208, 245, 253));
        thuongphatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cost-32.png"))); // NOI18N
        thuongphatLabel.setText("CHI PHÍ");
        thuongphatLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        thuongphatLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thuongphatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thuongphatLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thuongphatLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thuongphatLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout thuongphatPanelLayout = new javax.swing.GroupLayout(thuongphatPanel);
        thuongphatPanel.setLayout(thuongphatPanelLayout);
        thuongphatPanelLayout.setHorizontalGroup(
            thuongphatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thuongphatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        thuongphatPanelLayout.setVerticalGroup(
            thuongphatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thuongphatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        luongPanel.setBackground(new java.awt.Color(81, 113, 131));

        luongLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        luongLabel.setForeground(new java.awt.Color(208, 245, 253));
        luongLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-get-revenue-32.png"))); // NOI18N
        luongLabel.setText("DOANH THU");
        luongLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        luongLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        luongLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luongLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                luongLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                luongLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout luongPanelLayout = new javax.swing.GroupLayout(luongPanel);
        luongPanel.setLayout(luongPanelLayout);
        luongPanelLayout.setHorizontalGroup(
            luongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(luongLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        luongPanelLayout.setVerticalGroup(
            luongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(luongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhanvienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(hopdongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(khachPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(tourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(diadiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(luongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thuongphatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(802, 802, 802))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tourPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diadiemPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hopdongPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanvienPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thuongphatPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(luongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(134, 162, 154));
        jPanel2.setEnabled(false);

        jPanelTour.setLayout(new javax.swing.BoxLayout(jPanelTour, javax.swing.BoxLayout.LINE_AXIS));
        jPanelTour.setVisible (false);

        jPanelDiaDiem.setLayout(new javax.swing.BoxLayout(jPanelDiaDiem, javax.swing.BoxLayout.LINE_AXIS));
        jPanelDiaDiem.setVisible (false);

        jPanelKhach.setLayout(new javax.swing.BoxLayout(jPanelKhach, javax.swing.BoxLayout.LINE_AXIS));
        jPanelKhach.setVisible (false);

        jPanelNhanvien.setLayout(new javax.swing.BoxLayout(jPanelNhanvien, javax.swing.BoxLayout.LINE_AXIS));
        jPanelNhanvien.setVisible (false);

        jPanelDoan.setLayout(new javax.swing.BoxLayout(jPanelDoan, javax.swing.BoxLayout.LINE_AXIS));
        jPanelDoan.setVisible (false);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));
        jPanel11.setVisible (false);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));
        jPanel12.setVisible (false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1080, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(990, 650));
        jLabel1.setPreferredSize(new java.awt.Dimension(990, 650));

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));
        jPanel13.setVisible (false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTour.add (tourForm);
        //jPanel10.add(pb);
        jPanelDiaDiem.add(diadiemForm);
        //jPanel7.add(da);
        jPanelKhach.add(khachhangForm);
        //jPanel8.add (hd);
        jPanelNhanvien.add(nhanvienForm);
        //jPanel9.add(bcc);
        jPanelDoan.add(doanForm);
        //jPanel11.add(phucap);
        //jPanel12.add(luong);
        //jPanel13.add(thuongphat);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 990, 650));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));
        kGradientPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelMiniMouseClicked
    {//GEN-HEADEREND:event_jLabelMiniMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    /**
     *
     * @param hover
     * @param rand
     */
    public void changecolor(JPanel hover, Color rand)
    {
        hover.setBackground(rand);
    }

    public void changecolor1(JLabel hover1, Color rand)
    {
        hover1.setBackground(rand);
    }

    public void clickMenu(JPanel p1, JPanel p2, int numbool)
    {
        if (numbool == 1)
        {
            changecolor(p1, new Color(81, 113, 131));
            changecolor(p2, new Color(66, 98, 124));
        }
    }

    public void changeIcon(JLabel lb, String src)
    {
        ImageIcon ic = new ImageIcon(getClass().getResource(src));
        lb.setIcon(ic);
    }

    public void hideshowMenu(JPanel p, boolean check, JLabel lb)
    {
        if (check == true)
        {
            p.setPreferredSize(new Dimension(50, 650));
            changeIcon(lb, "/img/icons8_back_32.png");
//            p2.setPreferredSize (new Dimension (1200, 650));
        } else
        {
            p.setPreferredSize(new Dimension(260, 650));
            changeIcon(lb, "/img/icons8_menu_32.png");
//            p2.setPreferredSize (new Dimension (990, 650));
        }
    }

    private void jLabelClosedMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseClicked
    {//GEN-HEADEREND:event_jLabelClosedMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClosedMouseClicked

    private void jLabelMiniPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jLabelMiniPropertyChange
    {//GEN-HEADEREND:event_jLabelMiniPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMiniPropertyChange

    private void jLabelClosedMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseEntered
    {//GEN-HEADEREND:event_jLabelClosedMouseEntered
//        changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseEntered

    private void jLabelClosedMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseExited
    {//GEN-HEADEREND:event_jLabelClosedMouseExited
//         changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseExited

    private void btnHidemenuMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseEntered
    {//GEN-HEADEREND:event_btnHidemenuMouseEntered
        changecolor(linehideMenu, new Color(210, 226, 199));
    }//GEN-LAST:event_btnHidemenuMouseEntered

    private void btnHidemenuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseClicked
    {//GEN-HEADEREND:event_btnHidemenuMouseClicked
        clickMenu(hidemenu, logout, 1);
        if (check == true)
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//              changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = false;
        } else
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//            changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = true;
        }

    }//GEN-LAST:event_btnHidemenuMouseClicked

    private void btnHidemenuMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseExited
    {//GEN-HEADEREND:event_btnHidemenuMouseExited
        changecolor(linehideMenu, new Color(66, 98, 124));
    }//GEN-LAST:event_btnHidemenuMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseClicked
    {//GEN-HEADEREND:event_btnLogoutMouseClicked
        clickMenu(logout, hidemenu, 1);
        int confirm = JOptionPane.showConfirmDialog(DashBoard.this, "Bạn muốn đăng xuất?",
                "Xác Nhận", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == JOptionPane.OK_OPTION)
        {
            this.dispose(); ////  Exit Program
            LoginForm lg = new LoginForm();
            lg.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseEntered
    {//GEN-HEADEREND:event_btnLogoutMouseEntered
        changecolor(settingLogout, new Color(197, 64, 51));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseExited
    {//GEN-HEADEREND:event_btnLogoutMouseExited
        changecolor(settingLogout, new Color(66, 98, 124));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void diadiemLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_diadiemLabelMouseClicked
    {//GEN-HEADEREND:event_diadiemLabelMouseClicked
//       new CommbinedPanel(jPanel2,new phongbanForm ());
//        jPanel2.setLayout (null);
//        new CommbinedPanel(jPanel10,new phongbanForm ());
//        if (flagAcc == 0){
//            pb.initTablePb ();
//            jPanel10.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1 || flagAcc == 2){
//            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn truy cập Phòng Ban!");
//        }
        diadiemForm.initTableDiaDiem();
        jPanelTour.setVisible(false);
        jPanelDiaDiem.setVisible(true);
        jPanelNhanvien.setVisible(false);
        jPanelKhach.setVisible(false);
        jPanelDoan.setVisible(false);
    }//GEN-LAST:event_diadiemLabelMouseClicked

    private void diadiemLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_diadiemLabelMouseEntered
    {//GEN-HEADEREND:event_diadiemLabelMouseEntered
        changecolor(diadiemPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_diadiemLabelMouseEntered

    private void diadiemLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_diadiemLabelMouseExited
    {//GEN-HEADEREND:event_diadiemLabelMouseExited
        changecolor(diadiemPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_diadiemLabelMouseExited

    private void hopdongLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hopdongLabelMouseClicked
    {//GEN-HEADEREND:event_hopdongLabelMouseClicked
//        if (flagAcc == 0){
//            hd.initTablehd ();
//            jPanel8.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1){
//            hd.setFlagAcc(1);
//            hd.setMapb(mapb);
//            hd.initTablehdPB ();
//            jPanel8.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 2){
//            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn truy cập Hợp Đồng!");
//        }
        jPanelTour.setVisible(false);
        jPanelDiaDiem.setVisible(false);
        jPanelNhanvien.setVisible(false);
        jPanelKhach.setVisible(false);
        jPanelDoan.setVisible(true);
    }//GEN-LAST:event_hopdongLabelMouseClicked

    private void hopdongLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hopdongLabelMouseEntered
    {//GEN-HEADEREND:event_hopdongLabelMouseEntered
        changecolor(hopdongPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_hopdongLabelMouseEntered

    private void hopdongLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hopdongLabelMouseExited
    {//GEN-HEADEREND:event_hopdongLabelMouseExited
        changecolor(hopdongPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_hopdongLabelMouseExited

    private void khachLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_khachLabelMouseClicked
    {//GEN-HEADEREND:event_khachLabelMouseClicked
//        if (flagAcc == 0){
//            System.out.println ("click label BCC");
//            bcc.initTableBcc ();
//            jPanel9.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1){
//            System.out.println ("click label BCC");
//            bcc.setFlagAcc(1);
//            bcc.setMapb(mapb);
//            bcc.initTableBccPB ();
//            jPanel9.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 2){
//            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn truy cập Bảng Chấm Công!");
//        }
        jPanelTour.setVisible(false);
        jPanelDiaDiem.setVisible(false);
        jPanelNhanvien.setVisible(false);
        jPanelKhach.setVisible(true);
        jPanelDoan.setVisible(false);
    }//GEN-LAST:event_khachLabelMouseClicked

    private void khachLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_khachLabelMouseEntered
    {//GEN-HEADEREND:event_khachLabelMouseEntered
        changecolor(khachPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_khachLabelMouseEntered

    private void khachLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_khachLabelMouseExited
    {//GEN-HEADEREND:event_khachLabelMouseExited
        changecolor(khachPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_khachLabelMouseExited

    private void nhanvienLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nhanvienLabelMouseClicked
    {//GEN-HEADEREND:event_nhanvienLabelMouseClicked
//        System.out.println ("click label phụ cấp");
////       luong.setVisible (true);
//        if (flagAcc == 0){
//            phucap.initTablePcNv ();
//            jPanel11.setVisible (true);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1 || flagAcc == 2){
//            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn truy cập Phụ Cấp!");
//        }
        jPanelTour.setVisible(false);
        jPanelDiaDiem.setVisible(false);
        jPanelNhanvien.setVisible(true);
        jPanelKhach.setVisible(false);
        jPanelDoan.setVisible(false);
    }//GEN-LAST:event_nhanvienLabelMouseClicked

    private void nhanvienLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nhanvienLabelMouseEntered
    {//GEN-HEADEREND:event_nhanvienLabelMouseEntered
        changecolor(nhanvienPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_nhanvienLabelMouseEntered

    private void nhanvienLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nhanvienLabelMouseExited
    {//GEN-HEADEREND:event_nhanvienLabelMouseExited
        changecolor(nhanvienPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_nhanvienLabelMouseExited

    private void luongLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luongLabelMouseClicked
//        System.out.println ("click label luong");
////       luong.setVisible (true);
//        if (flagAcc == 0){
//            luong.setFlagAcc(0);
//            luong.bangluong.TinhLuong ();
//            luong.initTableLuong ();
//            jPanel12.setVisible (true);
//            jPanel11.setVisible (false);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1){
//            luong.setFlagAcc(1);
//            luong.setManv(account.getManhanvien());
//            luong.setMapb(mapb);
//            luong.bangluong.TinhLuong ();
//            luong.initTableLuongPB ();
//            jPanel12.setVisible (true);
//            jPanel11.setVisible (false);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 2){
//            luong.setFlagAcc(2);
//            luong.setManv(account.getManhanvien());
//            luong.bangluong.TinhLuong ();
//            luong.initTableLuongNV ();
//            jPanel12.setVisible (true);
//            jPanel11.setVisible (false);
//            jPanel4.setVisible (false);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel13.setVisible (false);
//        }
    }//GEN-LAST:event_luongLabelMouseClicked

    private void luongLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_luongLabelMouseEntered
    {//GEN-HEADEREND:event_luongLabelMouseEntered
        changecolor(luongPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_luongLabelMouseEntered

    private void luongLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_luongLabelMouseExited
    {//GEN-HEADEREND:event_luongLabelMouseExited
        changecolor(luongPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_luongLabelMouseExited

    private void tourLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourLabelMouseExited
        changecolor(tourPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_tourLabelMouseExited

    private void tourLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourLabelMouseEntered
        changecolor(tourPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_tourLabelMouseEntered

    private void tourLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourLabelMouseClicked
        //        CommbinedPanel cb= new CommbinedPanel(jPanel2,new nhanvienForm ());
        //        jPanel2.setLayout (null);
        //         new CommbinedPanel(jPanel4,new nhanvienForm ());
//        if (flagAcc == 0){
//            nv.initTableNhanvien ();
//            jPanel4.setVisible (true);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 1){
//            nv.setFlagAcc(1);
//            nv.setManv(account.getManhanvien());
//            nv.setMapb(mapb);
//            nv.initTableNhanvien ();
//            jPanel4.setVisible (true);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
//        if (flagAcc == 2){
//            nv.setFlagAcc(2);
//            nv.setManv(account.getManhanvien());
//            nv.initTableNhanvien ();
//            jPanel4.setVisible (true);
//            jPanel10.setVisible (false);
//            jPanel7.setVisible (false);
//            jPanel8.setVisible (false);
//            jPanel9.setVisible (false);
//            jPanel11.setVisible (false);
//            jPanel12.setVisible (false);
//            jPanel13.setVisible (false);
//        }
        tourForm.initTableTour();
        jPanelTour.setVisible(true);
        jPanelDiaDiem.setVisible(false);
        jPanelNhanvien.setVisible(false);
        jPanelKhach.setVisible(false);
        jPanelDoan.setVisible(false);
    }//GEN-LAST:event_tourLabelMouseClicked

    private void thuongphatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thuongphatLabelMouseClicked
        // TODO add your handling code here:
        if (flagAcc == 0)
        {
            System.out.println("click label ThuongPhat");
            //thuongphat.initTableTp();
            jPanel13.setVisible(true);
            jPanelDoan.setVisible(false);
            jPanelTour.setVisible(false);
            jPanelDiaDiem.setVisible(false);
            jPanelKhach.setVisible(false);
            jPanelNhanvien.setVisible(false);
            jPanel11.setVisible(false);
            jPanel12.setVisible(false);
        }
        if (flagAcc == 1)
        {
            System.out.println("click label ThuongPhat");
//            bcc.setFlagAcc(1);
//            bcc.setMapb(mapb);
//            bcc.initTableBccPB ();
            jPanel13.setVisible(true);
            jPanelDoan.setVisible(false);
            jPanelTour.setVisible(false);
            jPanelDiaDiem.setVisible(false);
            jPanelKhach.setVisible(false);
            jPanelNhanvien.setVisible(false);
            jPanel11.setVisible(false);
            jPanel12.setVisible(false);
        }
        if (flagAcc == 2)
        {
            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn truy cập Thưởng Phạt!");
        }
    }//GEN-LAST:event_thuongphatLabelMouseClicked

    private void thuongphatLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thuongphatLabelMouseEntered
        changecolor(thuongphatPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_thuongphatLabelMouseEntered

    private void thuongphatLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thuongphatLabelMouseExited
        changecolor(thuongphatPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_thuongphatLabelMouseExited

    public JLabel getjLabel5()
    {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5)
    {
        this.jLabel5 = jLabel5;
    }

//    public AccountDTO getAccount ()
//    {
//        return account;
//    }
//
//    public void setAccount (AccountDTO account)
//    {
//        this.account = account;
//    }
//    
//    public int getFlagAcc ()
//    {
//        return flagAcc;
//    }
//
//    public void setFlagAcc (int flagAcc)
//    {
//        this.flagAcc = flagAcc;
//    }
//    
//    public String getMapb ()
//    {
//        return mapb;
//    }
//
//    public void setMapb (String mapb)
//    {
//        this.mapb = mapb;
//    }
//
//    public nhanvienForm getNv()
//    {
//        return nv;
//    }
//
//    public void setNv(nhanvienForm nv)
//    {
//        this.nv = nv;
//    }
//
//    public phongbanForm getPb()
//    {
//        return pb;
//    }
//
//    public void setPb(phongbanForm pb)
//    {
//        this.pb = pb;
//    }
//
//    public duanForm getDa()
//    {
//        return da;
//    }
//
//    public void setDa(duanForm da)
//    {
//        this.da = da;
//    }
//
//    public hopdongForm getHd()
//    {
//        return hd;
//    }
//
//    public void setHd(hopdongForm hd)
//    {
//        this.hd = hd;
//    }
//
//    public BccForm getBcc()
//    {
//        return bcc;
//    }
//
//    public void setBcc(BccForm bcc)
//    {
//        this.bcc = bcc;
//    }
//
//    public phucapForm getPhucap()
//    {
//        return phucap;
//    }
//
//    public void setPhucap(phucapForm phucap)
//    {
//        this.phucap = phucap;
//    }
//
//    public LuongForm getLuong()
//    {
//        return luong;
//    }
//
//    public void setLuong(LuongForm luong)
//    {
//        this.luong = luong;
//    }
//
//    public thuongphatForm getThuongphat()
//    {
//        return thuongphat;
//    }
//
//    public void setThuongphat(thuongphatForm thuongphat)
//    {
//        this.thuongphat = thuongphat;
//    }
    public JLabel getBccLabel()
    {
        return khachLabel;
    }

    public void setBccLabel(JLabel bccLabel)
    {
        this.khachLabel = bccLabel;
    }

    public JLabel getBtnHidemenu()
    {
        return btnHidemenu;
    }

    public void setBtnHidemenu(JLabel btnHidemenu)
    {
        this.btnHidemenu = btnHidemenu;
    }

    public JLabel getBtnLogout()
    {
        return btnLogout;
    }

    public void setBtnLogout(JLabel btnLogout)
    {
        this.btnLogout = btnLogout;
    }

    public JLabel getHopdongLabel()
    {
        return hopdongLabel;
    }

    public void setHopdongLabel(JLabel hopdongLabel)
    {
        this.hopdongLabel = hopdongLabel;
    }

    public JLabel getLuongLabel()
    {
        return luongLabel;
    }

    public void setLuongLabel(JLabel luongLabel)
    {
        this.luongLabel = luongLabel;
    }

    public JLabel getNhanvienLabel()
    {
        return tourLabel;
    }

    public void setNhanvienLabel(JLabel nhanvienLabel)
    {
        this.tourLabel = nhanvienLabel;
    }

    public JLabel getPbLabel()
    {
        return diadiemLabel;
    }

    public void setPbLabel(JLabel pbLabel)
    {
        this.diadiemLabel = pbLabel;
    }

    public JLabel getPhucapLabel()
    {
        return nhanvienLabel;
    }

    public void setPhucapLabel(JLabel phucapLabel)
    {
        this.nhanvienLabel = phucapLabel;
    }

    public JLabel getThuongphatLabel()
    {
        return thuongphatLabel;
    }

    public void setThuongphatLabel(JLabel thuongphatLabel)
    {
        this.thuongphatLabel = thuongphatLabel;
    }

    public JLabel getjLabelClosed()
    {
        return jLabelClosed;
    }

    public void setjLabelClosed(JLabel jLabelClosed)
    {
        this.jLabelClosed = jLabelClosed;
    }

    public JLabel getjLabelMini()
    {
        return jLabelMini;
    }

    public void setjLabelMini(JLabel jLabelMini)
    {
        this.jLabelMini = jLabelMini;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHidemenu;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel diadiemLabel;
    private javax.swing.JPanel diadiemPanel;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JLabel hopdongLabel;
    private javax.swing.JPanel hopdongPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClosed;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelDiaDiem;
    private javax.swing.JPanel jPanelDoan;
    private javax.swing.JPanel jPanelKhach;
    private javax.swing.JPanel jPanelNhanvien;
    private javax.swing.JPanel jPanelTour;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel khachLabel;
    private javax.swing.JPanel khachPanel;
    private javax.swing.JPanel linehideMenu;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel luongLabel;
    private javax.swing.JPanel luongPanel;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JLabel nhanvienLabel;
    private javax.swing.JPanel nhanvienPanel;
    private javax.swing.JPanel settingLogout;
    private javax.swing.JLabel thuongphatLabel;
    private javax.swing.JPanel thuongphatPanel;
    private javax.swing.JLabel tourLabel;
    private javax.swing.JPanel tourPanel;
    // End of variables declaration//GEN-END:variables

//    public static void main (String[] args)
//    {
//        DashBoard l=new DashBoard ();
//        l.setVisible (true);
//    }
}
