/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.*;
import DTO.ChiPhiDTO;
import DTO.ChiTietDoanDTO;
import DTO.DoanDuLichDTO;
import DTO.LoaiChiPhiDTO;
import DTO.TourDTO;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import static ui.DashBoard.loadagain;

/**
 *
 * @author Hyung
 */
public class DoanhThuForm extends javax.swing.JPanel
{

    DefaultTableModel tbModelTKCP;
    private Utils ult = new Utils();

    /**
     * Creates new form jPanel2
     */
    public DoanhThuForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelThongkeCP = new javax.swing.JPanel();
        jButtonThongKe = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableThongke = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jDateNgayBDTK = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jDateNgayKTTK = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(233, 242, 249));
        setPreferredSize(new java.awt.Dimension(990, 650));

        jTabbedPane1.setBackground(new java.awt.Color(233, 242, 249));

        jPanelThongkeCP.setBackground(new java.awt.Color(233, 242, 249));
        jPanelThongkeCP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelThongkeCP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonThongKe.setText("Thống Kê");
        jButtonThongKe.setPreferredSize(new java.awt.Dimension(79, 30));
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongKeActionPerformed(evt);
            }
        });
        jPanelThongkeCP.add(jButtonThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 120, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setAutoscrolls(true);

        Vector tbColThongKe=new Vector();
        jTableThongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableThongkeMouseClicked(evt);
            }
        });
        tbColThongKe.add ("Mã Tour");
        tbColThongKe.add ("Tên Tour");
        tbColThongKe.add ("Mã Đoàn");
        tbColThongKe.add ("Tên Đoàn");
        tbColThongKe.add ("Giá Đoàn");
        tbColThongKe.add ("Ngày Đi");
        tbColThongKe.add ("Ngày Về");
        tbColThongKe.add ("Số Lượng Khách");
        tbColThongKe.add ("Tổng Tiền Nhận");
        tbColThongKe.add ("Tổng Chi Phí");
        tbColThongKe.add ("Tổng Doanh Thu");
        tbModelTKCP = new DefaultTableModel(tbColThongKe, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableThongke.setModel(tbModelTKCP);
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<TableModel>(tbModelTKCP);
        jTableThongke.setRowSorter(rowSorter);
        jTableThongke.setShowGrid(true);
        jTableThongke.setFocusable(false);
        jTableThongke.setIntercellSpacing(new Dimension(0,0));
        jTableThongke.setRowHeight(25);
        jTableThongke.getTableHeader().setOpaque(false);
        jTableThongke.setFillsViewportHeight(true);
        jTableThongke.getTableHeader().setBackground(new Color(232,57,99));
        jTableThongke.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableThongke.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableThongke.setSelectionBackground(new Color(52,152,219));
        jTableThongke.setGridColor(new java.awt.Color(83, 86, 88));

        jTableThongke.getColumn (tbColThongKe.elementAt (0)).setPreferredWidth (120);
        jTableThongke.getColumn (tbColThongKe.elementAt (1)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (2)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (3)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (4)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (5)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (6)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (7)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (8)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (9)).setPreferredWidth (150);
        jTableThongke.getColumn (tbColThongKe.elementAt (10)).setPreferredWidth (150);
        jTableThongke.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTableThongke);

        jPanelThongkeCP.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 950, 520));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("<html> <body>Ngày Băt Đầu<span style=\"color:rgb(216, 74, 67);\"> *</span> </body> </html> ");
        jPanelThongkeCP.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jDateNgayBDTK.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayBDTK.setDateFormatString("yyyy-MM-dd");
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) jDateNgayBDTK.getDateEditor();
        editor2.setEditable(false);
        jPanelThongkeCP.add(jDateNgayBDTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 30));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setText("<html> <body>Ngày Kết Thúc<span style=\"color:rgb(216, 74, 67);\"> *</span> </body> </html> ");
        jPanelThongkeCP.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 30));

        jDateNgayKTTK.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayKTTK.setDateFormatString("yyyy-MM-dd");
        JTextFieldDateEditor editor3 = (JTextFieldDateEditor) jDateNgayKTTK.getDateEditor();
        editor3.setEditable(false);
        jPanelThongkeCP.add(jDateNgayKTTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 180, 30));

        jTabbedPane1.addTab("Thống Kê Doanh Thu", jPanelThongkeCP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonThongKeActionPerformed
    {//GEN-HEADEREND:event_jButtonThongKeActionPerformed
        // TODO add your handling code here:
        tbModelTKCP.setRowCount(0);
        if (jDateNgayBDTK.getDate() == null || jDateNgayKTTK.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Ngày Bắt Đầu và Ngày Kết Thúc không được bỏ trống!");
            return;
        }
        String ngayBD = (String) ((JTextField) jDateNgayBDTK.getDateEditor().getUiComponent()).getText(),
                ngayKT = (String) ((JTextField) jDateNgayKTTK.getDateEditor().getUiComponent()).getText();
        //Validation
        StringBuilder message = new StringBuilder();
        Validation.afterOrEquals(message, "Ngày kết thúc", ngayKT, "Ngày bắt đầu", ngayBD);
        if(!message.toString().equals("")){
            JOptionPane.showMessageDialog(this, message.toString());
            return;
        }
        Date dateDoan = null;
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        for (DoanDuLichDTO doan : DashBoard.doanDuLichDTOs) {
            try {
                dateDoan = myFormat.parse(doan.getNgayKetThuc());
            } catch (ParseException ex) {
                Logger.getLogger(ChiPhiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (dateDoan != null
                    && (dateDoan.after(jDateNgayBDTK.getDate()) || dateDoan.equals(jDateNgayBDTK.getDate()))
                    && (dateDoan.before(jDateNgayKTTK.getDate()) || dateDoan.equals(jDateNgayKTTK.getDate()))) {
                long tongCP = 0;
                for (ChiPhiDTO chiPhi : DashBoard.chiPhiDTOs) {
                    if (chiPhi.getMaDoan().equals(doan.getMaDoan())) {
                        tongCP += Long.parseLong(chiPhi.getSoTien());
                    }
                }
//                tbColThongKe.add("Mã Tour");
//                tbColThongKe.add("Tên Tour");
//                tbColThongKe.add("Mã Đoàn");
//                tbColThongKe.add("Tên Đoàn");
//                tbColThongKe.add("Giá Đoàn");
//                tbColThongKe.add("Ngày Đi");
//                tbColThongKe.add("Ngày Về");
//                tbColThongKe.add("Số Lượng Khách");
//                tbColThongKe.add("Tổng Tiền Nhận");
//                tbColThongKe.add("Tổng Chi Phí");
//                tbColThongKe.add("Tổng Doanh Thu");
                Vector row = new Vector();
                for (TourDTO tour : DashBoard.tourDTOs) {
                    if (tour.getMaTour().equals(doan.getMaTour())) {
                        row.add(tour.getMaTour());
                        row.add(tour.getTenTour());
                        break;
                    }
                }
                row.add(doan.getMaDoan());
                row.add(doan.getTenDoan());
                row.add(doan.getGiaTour());
                row.add(doan.getNgayKhoiHanh());
                row.add(doan.getNgayKetThuc());
                int countKhach = 0;
                for (ChiTietDoanDTO ctDoan : DashBoard.chiTietDoanDTOs) {
                    if (ctDoan.getMaDoan().equals(doan.getMaDoan())) {
                        countKhach++;
                    }
                }
                row.add(countKhach);
                double tienNhan = Double.parseDouble(doan.getGiaTour())*countKhach;
                row.add(tienNhan);
                row.add(tongCP);
                row.add(tienNhan - tongCP);
                tbModelTKCP.addRow(row);
            }
        }
        jTableThongke.setModel(tbModelTKCP);
    }//GEN-LAST:event_jButtonThongKeActionPerformed

    private void jTableThongkeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableThongkeMouseClicked
    {//GEN-HEADEREND:event_jTableThongkeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableThongkeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonThongKe;
    private com.toedter.calendar.JDateChooser jDateNgayBDTK;
    private com.toedter.calendar.JDateChooser jDateNgayKTTK;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanelThongkeCP;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableThongke;
    // End of variables declaration//GEN-END:variables
}
