/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.GiaTourBUS;
import BUS.LoaiHinhTourBUS;
import BUS.TourBUS;
import BUS.Utils;
import DTO.DiaDiemThamQuanDTO;
import DTO.GiaTourDTO;
import DTO.LoaiHinhTourDTO;
import DTO.TourDTO;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyung
 */
public class DoanForm extends javax.swing.JPanel
{

    /**
     * Creates new form jPanel2
     */
    static int flagtkmk = 0;
    TourBUS tourBUS = new TourBUS();
    GiaTourBUS giaTourBUS = new GiaTourBUS();
    ChiTietTour chiTietTour = new ChiTietTour();
    LoaiHinhTourBUS loaiHinhTourBUS = new LoaiHinhTourBUS();
    public BufferedImage i = null;
    public String imgName = null;
    int rowTour, rowDiaDiemThamQuan, flagThemDiaDiem, rowLoaiHinh;
    private String maTour, tenTour, maLoai, maLoaiHienHanh, maGia, maGiaHienHanh, maTourChiTiet, tenTourChiTiet;
    private String maDiaDiem, tenDiaDiem, thuTu;
    private ArrayList<DiaDiemThamQuanDTO> diaDiemThamQuanTempArr;
    private Tour tour;
    Vector tbColDoan = new Vector();//Vector chứa các dòng dữ liệu của bảng.
    Vector tbColKhach = new Vector();//Vector chứa các tiêu đề của bảng.
    Vector tbColLoaiHinh = new Vector();
    Vector tbColNhanVien = new Vector();
    DefaultTableModel tbModelDoan, tbModelDiadiem, tbModelLoaiHinh, tbModelKhach, tbModelNhanVien;
    private Utils ult = new Utils();

    public DoanForm()
    {
        initComponents();
        //initTableTour();
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonChiPhi.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
        jBtnThemNV.setEnabled(true);
        jBtnSuaNV.setEnabled(false);
        jBtnHuyNV.setEnabled(true);
        jBtnXoaNV.setEnabled(false);
        jBtnChonNV.setEnabled(true);
        jBtnThemKhach.setEnabled(true);
        jBtnXoaKhach.setEnabled(false);
        jBtnHuyKhach.setEnabled(true);
    }

    public void loadDataTour()
    {
        tour = new Tour();
        tbModelDoan.setRowCount(0);
        tour.tableModelTour(tbModelDoan);
        jTableDoan.setModel(tbModelDoan);
    }

    public void initTableTour()
    {
        loadDataTour();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelQLTour = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextGiaTour = new javax.swing.JTextField();
        jDateNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jTextTenDoan = new javax.swing.JTextField();
        jTextLoaiTour = new javax.swing.JTextField();
        jBtnChonChiPhi = new javax.swing.JButton();
        jDateNgayBD = new com.toedter.calendar.JDateChooser();
        jBtnCapPhatMaTour = new javax.swing.JButton();
        jTextMadoan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLbManv = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextChiTiet = new javax.swing.JTextField();
        jLbManv1 = new javax.swing.JLabel();
        jTextChiPhi = new javax.swing.JTextField();
        jBtnChonTour = new javax.swing.JButton();
        jBtnThemTour = new javax.swing.JButton();
        jBtnXoaTour = new javax.swing.JButton();
        jBtnSuaTour = new javax.swing.JButton();
        jTextTimKiemDoan = new javax.swing.JTextField();
        jBtnTimKiemDoan = new javax.swing.JButton();
        jBtnRefreshDoan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDoan = new javax.swing.JTable();
        jBtnXemTour = new javax.swing.JButton();
        jBtnHuyTour = new javax.swing.JButton();
        jPanelChiTietTour = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextMaTour1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextTenTour1 = new javax.swing.JTextField();
        jPanelNhanVien = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextTenNV = new javax.swing.JTextField();
        jTextMaNV = new javax.swing.JTextField();
        jLbDiaDiem = new javax.swing.JLabel();
        jBtnThemNV = new javax.swing.JButton();
        jBtnSuaNV = new javax.swing.JButton();
        jTextNhiemVu = new javax.swing.JTextField();
        jBtnHuyNV = new javax.swing.JButton();
        jBtnXoaNV = new javax.swing.JButton();
        jLbThuTu1 = new javax.swing.JLabel();
        jBtnChonNV = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();
        jPanelKhachHang = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jTextTenKhach1 = new javax.swing.JTextField();
        jTextMaKhach1 = new javax.swing.JTextField();
        jBtnChonKhach1 = new javax.swing.JButton();
        jLbDiaDiem1 = new javax.swing.JLabel();
        jBtnThemKhach = new javax.swing.JButton();
        jTextSDT = new javax.swing.JTextField();
        jBtnHuyKhach = new javax.swing.JButton();
        jBtnXoaKhach = new javax.swing.JButton();
        jLbThuTu2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableKhachHang = new javax.swing.JTable();

        setBackground(new java.awt.Color(233, 242, 249));
        setPreferredSize(new java.awt.Dimension(990, 650));

        jTabbedPane1.setBackground(new java.awt.Color(233, 242, 249));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelQLTour.setBackground(new java.awt.Color(233, 242, 249));

        jPanel4.setBackground(new java.awt.Color(233, 242, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Ðoàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("<html> <body>Ngày Kết Thúc<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 30));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("<html> <body>Chi Tiết<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jTextGiaTour.setBackground(new java.awt.Color(214, 217, 223));
        jTextGiaTour.setForeground(new java.awt.Color(51, 51, 51));
        jTextGiaTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jTextGiaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 200, 30));

        jDateNgayKT.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayKT.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateNgayKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 200, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("<html> <body>Tên Ðoàn<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jTextTenDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenDoanActionPerformed(evt);
            }
        });
        jPanel4.add(jTextTenDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 30));

        jTextLoaiTour.setEditable(false);
        jTextLoaiTour.setBackground(new java.awt.Color(214, 217, 223));
        jPanel4.add(jTextLoaiTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 30));

        jBtnChonChiPhi.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonChiPhi.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonChiPhi.setText("...");
        jBtnChonChiPhi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonChiPhi.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonChiPhiActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnChonChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        jDateNgayBD.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayBD.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateNgayBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 200, 30));

        jBtnCapPhatMaTour.setBackground(new java.awt.Color(81, 113, 131));
        jBtnCapPhatMaTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_32.png"))); // NOI18N
        jBtnCapPhatMaTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCapPhatMaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapPhatMaTourActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnCapPhatMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 30, 30));

        jTextMadoan.setEditable(false);
        jTextMadoan.setBackground(new java.awt.Color(214, 217, 223));
        jTextChiPhi.setEditable(false);
        jPanel4.add(jTextMadoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("<html> <body> Mã Đoàn <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("<html> <body>Ngày Khởi Hành<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, 30));

        jLbManv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv.setText("<html> <body>Giá Tour<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setText("<html> <body>Loại Tour<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jTextChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChiTietActionPerformed(evt);
            }
        });
        jPanel4.add(jTextChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, 70));

        jLbManv1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv1.setText("<html> <body>Tổng Chi Phí<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 30));

        jTextChiPhi.setEditable(false);
        jTextChiPhi.setBackground(new java.awt.Color(214, 217, 223));
        jTextChiPhi.setForeground(new java.awt.Color(51, 51, 51));
        jTextChiPhi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jTextChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, 30));

        jBtnChonTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonTour.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonTour.setText("...");
        jBtnChonTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonTour.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonTourActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnChonTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jBtnThemTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThemTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThemTour.setText("Thêm");
        jBtnThemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemTourActionPerformed(evt);
            }
        });

        jBtnXoaTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoaTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoaTour.setText("Xóa");
        jBtnXoaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaTourActionPerformed(evt);
            }
        });

        jBtnSuaTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSuaTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSuaTour.setText("Sửa");
        jBtnSuaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaTourActionPerformed(evt);
            }
        });

        jBtnTimKiemDoan.setText("Tìm kiếm");
        jBtnTimKiemDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTimKiemDoanActionPerformed(evt);
            }
        });

        jBtnRefreshDoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefreshDoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefreshDoan.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefreshDoan.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefreshDoan.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefreshDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshDoanActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTableDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDoanMouseClicked(evt);
            }
        });
        tbColDoan.add("Mă Ðoàn");
        tbColDoan.add("Tên Ðoàn");
        tbColDoan.add("Tên Tour");
        tbColDoan.add("Giá Tour");
        tbColDoan.add("Ngày Khởi Hành");
        tbColDoan.add("Ngày Kết Thúc");

        tbModelDoan= new DefaultTableModel(tbColDoan,40){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableDoan.setModel (tbModelDoan);
        jTableDoan.setShowGrid(true);
        jTableDoan.setFocusable(false);
        jTableDoan.setIntercellSpacing(new Dimension(0,0));
        jTableDoan.setRowHeight(25);
        jTableDoan.getTableHeader().setOpaque(false);
        jTableDoan.setFillsViewportHeight(true);
        jTableDoan.getTableHeader().setBackground(new Color(232,57,99));
        jTableDoan.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableDoan.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableDoan.setSelectionBackground(new Color(52,152,219));
        jScrollPane1.setViewportView(jTableDoan);
        jTableDoan.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        jBtnXemTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXemTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXemTour.setText("Xem");
        jBtnXemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXemTourActionPerformed(evt);
            }
        });

        jBtnHuyTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuyTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuyTour.setText("Hủy");
        jBtnHuyTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQLTourLayout = new javax.swing.GroupLayout(jPanelQLTour);
        jPanelQLTour.setLayout(jPanelQLTourLayout);
        jPanelQLTourLayout.setHorizontalGroup(
            jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(jTextTimKiemDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnTimKiemDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefreshDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBtnXoaTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSuaTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnXemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelQLTourLayout.setVerticalGroup(
            jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnXemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jBtnSuaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jBtnXoaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnRefreshDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTimKiemDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnTimKiemDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Quản Lý Ðoàn", jPanelQLTour);

        jPanelChiTietTour.setBackground(new java.awt.Color(233, 242, 249));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("<html> <body> Mã Đoàn <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");

        jTextMaTour1.setEditable(false);
        jTextMaTour1.setBackground(new java.awt.Color(214, 217, 223));
        jTextChiPhi.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setText("<html> <body>Tên Đoàn<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");

        jTextTenTour1.setEditable(false);
        jTextTenTour1.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenTour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenTour1ActionPerformed(evt);
            }
        });

        jPanelNhanVien.setBackground(new java.awt.Color(233, 242, 249));
        jPanelNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanelNhanVien.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanelNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("<html> <body>Mã Nhân Viên<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanelNhanVien.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jTextTenNV.setEditable(false);
        jTextTenNV.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenNV.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenNV.setRequestFocusEnabled(false);
        jPanelNhanVien.add(jTextTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, 30));

        jTextMaNV.setEditable(false);
        jTextMaNV.setBackground(new java.awt.Color(214, 217, 223));
        jPanelNhanVien.add(jTextMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 160, 30));

        jLbDiaDiem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbDiaDiem.setText("<html> <body>Tên Nhân Viên<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanelNhanVien.add(jLbDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jBtnThemNV.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThemNV.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThemNV.setText("Thêm");
        jBtnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemNVActionPerformed(evt);
            }
        });
        jPanelNhanVien.add(jBtnThemNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 40));

        jBtnSuaNV.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSuaNV.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSuaNV.setText("Sửa");
        jBtnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaNVActionPerformed(evt);
            }
        });
        jPanelNhanVien.add(jBtnSuaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 40));

        jTextNhiemVu.setForeground(new java.awt.Color(51, 51, 51));
        jTextNhiemVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelNhanVien.add(jTextNhiemVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, 30));

        jBtnHuyNV.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuyNV.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuyNV.setText("Hủy");
        jBtnHuyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyNVActionPerformed(evt);
            }
        });
        jPanelNhanVien.add(jBtnHuyNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, 40));

        jBtnXoaNV.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoaNV.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoaNV.setText("Xóa");
        jBtnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaNVActionPerformed(evt);
            }
        });
        jPanelNhanVien.add(jBtnXoaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, 40));

        jLbThuTu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbThuTu1.setText("<html> <body>Nhiệm Vụ<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanelNhanVien.add(jLbThuTu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jBtnChonNV.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonNV.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonNV.setText("...");
        jBtnChonNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonNV.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonNVActionPerformed(evt);
            }
        });
        jPanelNhanVien.add(jBtnChonNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableNhanVien.setAutoCreateRowSorter(true);
        jTableNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanVienMouseClicked(evt);
            }
        });
        tbColNhanVien.add("Mă Nhân Viên");
        tbColNhanVien.add("Tên Nhân Viên");
        tbColNhanVien.add("Nhiệm Vụ");
        tbModelNhanVien= new DefaultTableModel(tbColNhanVien,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableNhanVien.setModel (tbModelNhanVien);
        jTableNhanVien.setShowGrid(true);
        jTableNhanVien.setFocusable(false);
        jTableNhanVien.setIntercellSpacing(new Dimension(0,0));
        jTableNhanVien.setRowHeight(25);
        jTableNhanVien.getTableHeader().setOpaque(false);
        jTableNhanVien.setFillsViewportHeight(true);
        jTableNhanVien.getTableHeader().setBackground(new Color(232,57,99));
        jTableNhanVien.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableNhanVien.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableNhanVien.setSelectionBackground(new Color(52,152,219));
        jTableNhanVien.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTableNhanVien);

        jPanelKhachHang.setBackground(new java.awt.Color(233, 242, 249));
        jPanelKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanelKhachHang.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanelKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setText("<html> <body>Mã Khách<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanelKhachHang.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jTextTenKhach1.setEditable(false);
        jTextTenKhach1.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenKhach1.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenKhach1.setRequestFocusEnabled(false);
        jPanelKhachHang.add(jTextTenKhach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 30));

        jTextMaKhach1.setEditable(false);
        jTextMaKhach1.setBackground(new java.awt.Color(214, 217, 223));
        jPanelKhachHang.add(jTextMaKhach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 30));

        jBtnChonKhach1.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonKhach1.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonKhach1.setText("...");
        jBtnChonKhach1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonKhach1.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonKhach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonKhach1ActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(jBtnChonKhach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLbDiaDiem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbDiaDiem1.setText("<html> <body>Tên Khách<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanelKhachHang.add(jLbDiaDiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jBtnThemKhach.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThemKhach.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThemKhach.setText("Thêm");
        jBtnThemKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemKhachActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(jBtnThemKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 40));

        jTextSDT.setEditable(false);
        jTextSDT.setBackground(new java.awt.Color(214, 217, 223));
        jTextSDT.setForeground(new java.awt.Color(51, 51, 51));
        jTextSDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelKhachHang.add(jTextSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        jBtnHuyKhach.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuyKhach.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuyKhach.setText("Hủy");
        jBtnHuyKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyKhachActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(jBtnHuyKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 40));

        jBtnXoaKhach.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoaKhach.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoaKhach.setText("Xóa");
        jBtnXoaKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaKhachActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(jBtnXoaKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 80, 40));

        jLbThuTu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbThuTu2.setText("<html> <body>Số Điện Thoại<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanelKhachHang.add(jLbThuTu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableKhachHang.setAutoCreateRowSorter(true);
        jTableKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKhachHangMouseClicked(evt);
            }
        });
        tbColKhach.add("Mă Khách");
        tbColKhach.add("Tên Khách");
        tbColKhach.add("SÐT");
        tbModelKhach= new DefaultTableModel(tbColKhach,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableKhachHang.setModel (tbModelKhach);
        jTableKhachHang.setShowGrid(true);
        jTableKhachHang.setFocusable(false);
        jTableKhachHang.setIntercellSpacing(new Dimension(0,0));
        jTableKhachHang.setRowHeight(25);
        jTableKhachHang.getTableHeader().setOpaque(false);
        jTableKhachHang.setFillsViewportHeight(true);
        jTableKhachHang.getTableHeader().setBackground(new Color(232,57,99));
        jTableKhachHang.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableKhachHang.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableNhanVien.setSelectionBackground(new Color(52,152,219));
        jTableKhachHang.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(jTableKhachHang);

        javax.swing.GroupLayout jPanelChiTietTourLayout = new javax.swing.GroupLayout(jPanelChiTietTour);
        jPanelChiTietTour.setLayout(jPanelChiTietTourLayout);
        jPanelChiTietTourLayout.setHorizontalGroup(
            jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChiTietTourLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextMaTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextTenTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChiTietTourLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(jPanelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanelChiTietTourLayout.setVerticalGroup(
            jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChiTietTourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTenTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi Tiết Ðoàn", jPanelChiTietTour);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String ktra()
    {
        /*String temp = "";
        if (jTextMaLoaiHinh.getText().equals("")) {
            temp += "Vui lòng cấp phát mã nhân viên!\n";
        }

        String hoten = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s]{5,32}$";
        if (!Pattern.matches(hoten, jTextHonv.getText())) {
            temp += "- Họ Nhân Viên không hợp lệ!\n";
        }

        String ten = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s]{2,32}$";
        if (!Pattern.matches(ten, jTextTenLoaiHinh.getText())) {
            temp += "- Tên Nhân Viên không hợp lệ!\n";
        }
        String ngaysinh = ((JTextField) jDateNgaySinh.getDateEditor().getUiComponent()).getText();
        String ngaycmnd = ((JTextField) jDateNgaycapcmnd.getDateEditor().getUiComponent()).getText();
        if (ngaysinh.equals("")) {
            temp += "- Ngày sinh không được để trống!\n";
        }
        if (ngaycmnd.equals("")) {
            temp += "- Ngày cấp CMND không được để trống!\n";
        }
        if (!ngaysinh.equals("") && !ngaycmnd.equals("")) {
            String[] arrNgaySinh = ngaysinh.split("-");
            String[] arrNgayCap = ngaycmnd.split("-");
            if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) < 14) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            } else if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) == 14 && Integer.parseInt(arrNgayCap[1]) - Integer.parseInt(arrNgaySinh[1]) < 0) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            } else if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) == 14 && Integer.parseInt(arrNgayCap[1]) - Integer.parseInt(arrNgaySinh[1]) == 0 && Integer.parseInt(arrNgayCap[2]) - Integer.parseInt(arrNgaySinh[2]) < 0) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            }
        }

        String noisinh = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(noisinh, jTextNoiSinh.getText())) {
            temp += "- Nơi Sinh không hợp lệ!\n";
        }

        String trinhdo = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(trinhdo, jTextTdhv.getText())) {
            temp += "- Trình Độ Học Vấn không hợp lệ!\n";
        }

        String diachi = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(diachi, jTextDiaChi.getText())) {
            temp += "- Địa Chỉ không hợp lệ!\n";
        }

        String cmnd = "^\\d{12}$|^\\d{9}$";
        if (!Pattern.matches(cmnd, jTextCmnd.getText())) {
            temp += "- CMND không hợp lệ!\n";
        }

        String sdt = "^\\d{8}$|(^[0]+[1-9]\\d{8})$";
        if (!Pattern.matches(sdt, jTextSDT.getText())) {
            temp += "- Số Điện Thoại không hợp lệ!\n";
        }

        String gmail = "^[a-zA-z]+[a-zA-z0-9]+@+[azA-z0-9]+.+com$";
        if (!Pattern.matches(gmail, jTextEmail.getText())) {
            temp += "- Email không hợp lệ!\n";
        }
//        System.out.println(jDateNgaySinh.get());

        String luongcb = "([\\d]+.[\\d]+|[\\d]+)";
        if (!Pattern.matches(luongcb, jTextLuongcb.getText())) {
            temp += "- Lương Căn Bản không hợp lệ!\n";
        }*/
        return "";
    }

    private void jBtnThemTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemTourActionPerformed
        // TODO add your handling code here:jBtnCapPhatMaTour.setEnabled(true);
        String maTour = (String) jTextMadoan.getText(),
                tenTour = (String) jTextTenDoan.getText(),
                giaTour = (String) jTextGiaTour.getText(),
                ngayBD = (String) ((JTextField) jDateNgayBD.getDateEditor().getUiComponent()).getText(),
                ngayKT = (String) ((JTextField) jDateNgayKT.getDateEditor().getUiComponent()).getText();
        if (tourBUS.themTour(maTour, (String) getMaLoai(), tenTour,
                (String) jTextChiTiet.getText(), giaTour, ngayBD, ngayKT))
        {
            Vector newrow = new Vector();
            newrow.add(maTour);
            newrow.add(tenTour);
            newrow.add((String) jTextLoaiTour.getText());
            newrow.add(giaTour);
            newrow.add(ngayBD);
            newrow.add(ngayKT);
            tbModelDoan.addRow(newrow);
            JOptionPane.showMessageDialog(this, "Thêm Tour thành công!");
        } else
        {
            JOptionPane.showMessageDialog(this, "Thêm Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMadoan.setText("");
        jTextTenDoan.setText("");
        jTextLoaiTour.setText("");
        jTextChiTiet.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonChiPhi.setEnabled(false);
//        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnThemTourActionPerformed

    private void jBtnHuyNVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyNVActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyNVActionPerformed
        // TODO add your handling code here:
        jBtnChonNV.setEnabled(true);
        jBtnThemNV.setEnabled(false);
        jBtnSuaNV.setEnabled(false);
        jBtnXoaNV.setEnabled(false);
        jBtnHuyNV.setEnabled(false);
//        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnHuyNVActionPerformed

    private void jBtnRefreshDoanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnRefreshDoanActionPerformed
    {//GEN-HEADEREND:event_jBtnRefreshDoanActionPerformed
        //        // TODO add your handling code here:
        //        jTextTimKiemNV.setText("");
        //        tbnv.loadDataNV();
        //        tbModelTour.setRowCount(0);
        //        tbnv.bangnhanvien(tbModelTour);
        jTextTimKiemDoan.setText("");
        loadDataTour();
    }//GEN-LAST:event_jBtnRefreshDoanActionPerformed

    private void jBtnTimKiemDoanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnTimKiemDoanActionPerformed
    {//GEN-HEADEREND:event_jBtnTimKiemDoanActionPerformed
        // TODO add your handling code here:
        //        String manv = jTextTimKiemNV.getText();
        //        tbnv.searchbangnhanvien(tbModelTour, manv);
        //        jTable1.setModel(tbModelTour);
        //        System.out.println("click tim kiem");
    }//GEN-LAST:event_jBtnTimKiemDoanActionPerformed

    private void jBtnCapPhatMaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnCapPhatMaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnCapPhatMaTourActionPerformed
        // TODO add your handling code here:
        loadDataTour();
        String init = null;
        init = tourBUS.CapPhat(init);
        jTextMadoan.setText(init);
        jBtnCapPhatMaTour.setEnabled(false);
        jBtnThemTour.setEnabled(true);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(true);
        jBtnXemTour.setEnabled(false);
        jTextTenDoan.setText("");
        jTextLoaiTour.setText("");
        jTextChiTiet.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(true);
        jTextGiaTour.setBackground(new Color(255, 255, 255));
        jBtnChonChiPhi.setEnabled(true);
//        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(true);
        jDateNgayKT.setEnabled(true);
    }//GEN-LAST:event_jBtnCapPhatMaTourActionPerformed

    private void jBtnChonChiPhiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonChiPhiActionPerformed
    {//GEN-HEADEREND:event_jBtnChonChiPhiActionPerformed
        // TODO add your handling code here:
        BangChiPhi BangChiPhi = new BangChiPhi();
//        bangLoaiHinh.tourForm = this;
        BangChiPhi.doanForm = this;
    }//GEN-LAST:event_jBtnChonChiPhiActionPerformed

    private void jBtnXoaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaTourActionPerformed
        // TODO add your handling code here:
        if (tourBUS.xoaTour(maTour))
        {
            tbModelDoan.removeRow(rowTour);
            JOptionPane.showMessageDialog(this, "Xóa Tour thành công!");
        } else
        {
            JOptionPane.showMessageDialog(this, "Xóa Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMadoan.setText("");
        jTextTenDoan.setText("");
        jTextLoaiTour.setText("");
        jTextChiTiet.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonChiPhi.setEnabled(false);
//        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnXoaTourActionPerformed

    private void jBtnSuaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaTourActionPerformed
        // TODO add your handling code here:
        String tenTour = (String) jTextTenDoan.getText(),
                ngayBD = (String) ((JTextField) jDateNgayBD.getDateEditor().getUiComponent()).getText(),
                ngayKT = (String) ((JTextField) jDateNgayKT.getDateEditor().getUiComponent()).getText();
        System.out.println("Sua tour: " + maTour);
        if (tourBUS.suaTour(getMaTour(), tenTour, (String) jTextChiTiet.getText(), getMaLoaiHienHanh(), getMaLoai(), getMaGiaHienHanh(), getMaGia()))
        {
            tbModelDoan.setValueAt(tenTour, rowTour, 1);
            tbModelDoan.setValueAt(jTextLoaiTour.getText(), rowTour, 2);
            tbModelDoan.setValueAt(jTextGiaTour.getText(), rowTour, 3);
            tbModelDoan.setValueAt(ngayBD, rowTour, 4);
            tbModelDoan.setValueAt(ngayKT, rowTour, 5);
            JOptionPane.showMessageDialog(this, "Sửa Tour thành công!");
        } else
        {
            JOptionPane.showMessageDialog(this, "Sửa Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMadoan.setText("");
        jTextTenDoan.setText("");
        jTextLoaiTour.setText("");
        jTextChiTiet.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonChiPhi.setEnabled(false);
//        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnSuaTourActionPerformed

    private void jTextTenDoanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenDoanActionPerformed
    {//GEN-HEADEREND:event_jTextTenDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenDoanActionPerformed

    private void jTextTenTour1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenTour1ActionPerformed
    {//GEN-HEADEREND:event_jTextTenTour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenTour1ActionPerformed

    private void jBtnChonNVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonNVActionPerformed
    {//GEN-HEADEREND:event_jBtnChonNVActionPerformed
        // TODO add your handling code here:
        BangNhanVien bangNhanVien = new BangNhanVien();
        bangNhanVien.doanForm = this;
//        bangDiaDiem.tourForm = this;
//        bangDiaDiem.loadData();
    }//GEN-LAST:event_jBtnChonNVActionPerformed

    private void jBtnXoaNVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaNVActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaNVActionPerformed
        // TODO add your handling code here:
        Vector row = new Vector();
        row.add(jTextMaNV.getText());
        row.add(jTextTenNV.getText());
        row.add(Integer.parseInt(jTextNhiemVu.getText()));
        if (chiTietTour.deleteDiaDiemThamQuan(maTourChiTiet, jTextMaNV.getText(), Integer.parseInt(jTextNhiemVu.getText())))
        {
            tbModelDiadiem.removeRow(rowDiaDiemThamQuan);
        } else
        {
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonNV.setEnabled(true);
        jBtnThemNV.setEnabled(false);
        jBtnSuaNV.setEnabled(false);
        jBtnXoaNV.setEnabled(false);
        jBtnHuyNV.setEnabled(false);
//        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnXoaNVActionPerformed

    private void jBtnThemNVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThemNVActionPerformed
    {//GEN-HEADEREND:event_jBtnThemNVActionPerformed
        // TODO add your handling code here:
        Vector row = new Vector();
        row.add(jTextMaNV.getText());
        row.add(jTextTenNV.getText());
        row.add(Integer.parseInt(jTextNhiemVu.getText()));
//        DiaDiemThamQuanDTO temp = new DiaDiemThamQuanDTO(jTextMaDiaDiem.getText(),maTourChiTiet,Integer.parseInt(jTextThuTu.getText()));
//        //System.out.println(jTextThuTu.getText());
//        int flag = 1;
//        for(DiaDiemThamQuanDTO a : chiTietTour.DiaDiemThamQuanDTOs()){
//            if(a.getMaDiaDiem().equals(jTextMaDiaDiem.getText())&&(a.getThuTu()==(Integer.parseInt(jTextThuTu.getText())))){
//                    flag=0;
//                    //System.out.println("Dup");
//                    break;
//                };
//            }
//        if(flag==1&&!jTextMaDiaDiem.getText().equals("")&&!jTextTenDiaDiem.getText().equals("")&&!jTextThuTu.getText().equals("")&&chiTietTour.checkDuplicateThuTu(maTourChiTiet,Integer.parseInt(jTextThuTu.getText()))){
//            tbModelDiadiem.addRow(row);
//            
//        }else {
//            System.out.println("Trùng hoặc rỗng");
//        }
        if (chiTietTour.addDiaDiemThamQuan(maTourChiTiet, jTextMaNV.getText(), Integer.parseInt(jTextNhiemVu.getText())))
        {
            tbModelDiadiem.addRow(row);
        } else
        {
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonNV.setEnabled(true);
        jBtnThemNV.setEnabled(false);
        jBtnSuaNV.setEnabled(false);
        jBtnXoaNV.setEnabled(false);
        jBtnHuyNV.setEnabled(false);
//        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnThemNVActionPerformed

    private void jBtnSuaNVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaNVActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaNVActionPerformed
        // TODO add your handling code here:
        //        int flag = 1;
//        if(diaDiemThamQuanTempArr.size()>0){
//            System.out.println("hello");
//            for(DiaDiemThamQuanDTO a : diaDiemThamQuanTempArr){
//                System.out.println(a.elementAt(2)+" "+jTextThuTu.getText());
//                if(a.elementAt(2).equals(jTextThuTu.getText())){
//                    flag=0;
//                    System.out.println();
//                    //break;
//                };
//            }
//        }
//        if(flag==1&&chiTietTour.checkDuplicateThuTu(maTourChiTiet,Integer.parseInt(jTextThuTu.getText()))){
//            if(diaDiemThamQuanTempArr.size()>0){
//                for(Vector a : diaDiemThamQuanTempArr){
//                    if(a.elementAt(0).equals(jTextMaDiaDiem.getText())&&a.elementAt(2).equals(tbModelDiadiem.getValueAt(rowDiaDiemThamQuan, 2))){
//                        a.setElementAt(jTextThuTu.getText(), 2);
//                        break;
//                    }
//                }
//            }
//            tbModelDiadiem.setValueAt(jTextThuTu.getText(), rowDiaDiemThamQuan, 2);
//   
        if (chiTietTour.updateDiaDiemThamQuan(maTourChiTiet, jTextMaNV.getText(), (int) tbModelDiadiem.getValueAt(rowDiaDiemThamQuan, 2), Integer.parseInt(jTextNhiemVu.getText())))
        {
            tbModelDiadiem.setValueAt(jTextNhiemVu.getText(), rowDiaDiemThamQuan, 2);
        } else
        {
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonNV.setEnabled(true);
        if (flagThemDiaDiem == 1)
        {
            jBtnThemNV.setEnabled(true);
        } else
        {
            jBtnThemNV.setEnabled(false);
        }
        jBtnSuaNV.setEnabled(false);
        jBtnXoaNV.setEnabled(false);
        jBtnHuyNV.setEnabled(false);
//        jBtnLuuDD.setEnabled(true);
    }//GEN-LAST:event_jBtnSuaNVActionPerformed

    private void jTableNhanVienMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableNhanVienMouseClicked
    {//GEN-HEADEREND:event_jTableNhanVienMouseClicked
        // TODO add your handling code here:
        rowDiaDiemThamQuan = jTableNhanVien.getSelectedRow();
        jTextMaNV.setText((String) jTableNhanVien.getValueAt(rowDiaDiemThamQuan, 0));
        //System.out.println((String) jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 0));
        jTextTenNV.setText((String) jTableNhanVien.getValueAt(rowDiaDiemThamQuan, 1));
        jTextNhiemVu.setText(Integer.toString((int) jTableNhanVien.getValueAt(rowDiaDiemThamQuan, 2)));
        //System.out.println(Integer.toString( Integer.parseInt((String)jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 2))));
        if (flagThemDiaDiem == 1)
        { // NẾU TOUR CHƯA CÓ ĐOÀN
            jBtnChonNV.setEnabled(false);
            jBtnThemNV.setEnabled(false);
            jBtnSuaNV.setEnabled(true);
            jBtnXoaNV.setEnabled(true);
            jBtnHuyNV.setEnabled(true);
//            jBtnLuuDD.setEnabled(false);
        } else
        { // NẾU CÓ ĐOÀN
            jBtnChonNV.setEnabled(false);
            jBtnThemNV.setEnabled(false);
            jBtnSuaNV.setEnabled(false);
            jBtnXoaNV.setEnabled(false);
            jBtnHuyNV.setEnabled(false);
//            jBtnLuuDD.setEnabled(false);
        }
    }//GEN-LAST:event_jTableNhanVienMouseClicked

    private void jBtnXemTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXemTourActionPerformed
    {//GEN-HEADEREND:event_jBtnXemTourActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        rowTour = jTableDoan.getSelectedRow();
        maTourChiTiet = (String) jTableDoan.getModel().getValueAt(rowTour, 0);
        tenTourChiTiet = (String) jTableDoan.getModel().getValueAt(rowTour, 1);
        jTextMaTour1.setText(maTourChiTiet);//System.out.println(maTourChiTiet);
        jTextTenTour1.setText(tenTour);
        System.out.println(tenTour);
        tbModelDoan.setRowCount(0);
        tbModelDiadiem.setRowCount(0);
        chiTietTour.tbModelDiaDiemThamQuan(tbModelDiadiem, maTourChiTiet);
        chiTietTour.tbModelDoanDuLich(tbModelDoan, maTourChiTiet);
        System.out.println(chiTietTour.countDoanTrongTour(maTourChiTiet));
        System.out.println(maTourChiTiet);
        if (chiTietTour.countDoanTrongTour(maTourChiTiet) == 0)
        { // NẾU TOUR CHƯA CÓ ĐOÀN
            flagThemDiaDiem = 1;
            jBtnChonNV.setEnabled(true);
            jBtnThemNV.setEnabled(false);
            jBtnSuaNV.setEnabled(false);
            jBtnXoaNV.setEnabled(false);
            jBtnHuyNV.setEnabled(false);
//            jBtnLuuDD.setEnabled(false);
        } else
        { // NẾU CÓ ĐOÀN
            flagThemDiaDiem = 0;
            jBtnChonNV.setEnabled(false);
            jBtnThemNV.setEnabled(false);
            jBtnSuaNV.setEnabled(false);
            jBtnXoaNV.setEnabled(false);
            jBtnHuyNV.setEnabled(false);
//            jBtnLuuDD.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnXemTourActionPerformed

    private void jBtnHuyTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyTourActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyTourActionPerformed
        // TODO add your handling code here:
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMadoan.setText("");
        jTextTenDoan.setText("");
        jTextLoaiTour.setText("");
        jTextChiTiet.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
//        jBtnChonGiaTour.setEnabled(false);
        jBtnChonChiPhi.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnHuyTourActionPerformed

    private void jTextChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChiTietActionPerformed

    private void jTableDoanMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableDoanMouseClicked
    {//GEN-HEADEREND:event_jTableDoanMouseClicked
        if (evt.getSource() == jTableDoan)
        {
            rowTour = jTableDoan.getSelectedRow();
            if (rowTour != -1)
            {
                maTour = (String) jTableDoan.getModel().getValueAt(rowTour, 0);
                tenTour = (String) jTableDoan.getModel().getValueAt(rowTour, 1);
                if (!maTour.equals("null"))
                {
                    jTextMadoan.setText(maTour);
                    jTextTenDoan.setText(tenTour);
                    jTextLoaiTour.setText((String) jTableDoan.getModel().getValueAt(rowTour, 2));
                    jTextGiaTour.setText((String) jTableDoan.getModel().getValueAt(rowTour, 3));
                    try
                    {
                        Date dateBD = new SimpleDateFormat("yyyy-MM-dd").parse(jTableDoan.getModel().getValueAt(rowTour, 4).toString());
                        jDateNgayBD.setDate(dateBD);
                    } catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(DoanForm.this, e);
                        System.out.println("- Load sai ngày bắt đầu!");
                    }
                    try
                    {
                        Date dateKT = new SimpleDateFormat("yyyy-MM-dd").parse(jTableDoan.getModel().getValueAt(rowTour, 5).toString());
                        jDateNgayKT.setDate(dateKT);
                    } catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(DoanForm.this, e);
                        System.out.println("- Load sai ngày kết thúc!");
                    }
                    for (TourDTO tour : tourBUS.getTourDTOS())
                    {
                        if (maTour.equals(tour.getMaTour()))
                        {
                            jTextChiTiet.setText(tour.getDacDiem());
                            setMaLoaiHienHanh(tour.getMaLoai());
                            setMaLoai(tour.getMaLoai());
                        }
                    }
                    setMaTour(maTour);
                    System.out.println("maTour: " + getMaTour());
                    System.out.println("maLoaiHH: " + getMaLoaiHienHanh());
                    for (GiaTourDTO giaTour : giaTourBUS.getGiaTourDTOs())
                    {
                        if (giaTour.getMaTour().equals(getMaTour()) && giaTour.getHienHanh() == 1)
                        {
                            setMaGiaHienHanh(giaTour.getMaGia());
                            setMaGia(giaTour.getMaGia());
                        }
                    }
                    System.out.println("maGiaHH: " + getMaGiaHienHanh());
                    jBtnCapPhatMaTour.setEnabled(false);
                    jBtnThemTour.setEnabled(false);
                    jBtnSuaTour.setEnabled(true);
                    jBtnXoaTour.setEnabled(true);
                    jBtnHuyTour.setEnabled(true);
                    jBtnXemTour.setEnabled(true);
                    jTextGiaTour.setEditable(false);
                    jTextGiaTour.setBackground(new Color(214, 217, 223));
                    jBtnChonChiPhi.setEnabled(true);

                    jDateNgayBD.setEnabled(false);
                    jDateNgayKT.setEnabled(false);
                } else
                {
                    jBtnCapPhatMaTour.setEnabled(true);
                    jBtnThemTour.setEnabled(false);
                    jBtnSuaTour.setEnabled(false);
                    jBtnXoaTour.setEnabled(false);
                    jBtnHuyTour.setEnabled(false);
                    jBtnXemTour.setEnabled(false);
                    jTextGiaTour.setEditable(false);
                    jTextGiaTour.setBackground(new Color(214, 217, 223));
                    jBtnChonChiPhi.setEnabled(false);

                    jDateNgayBD.setEnabled(false);
                    jDateNgayKT.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_jTableDoanMouseClicked

    private void jBtnChonKhach1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonKhach1ActionPerformed
    {//GEN-HEADEREND:event_jBtnChonKhach1ActionPerformed
        // TODO add your handling code here:
        BangKhach bangKhach = new BangKhach();
        bangKhach.doanForm = this;
    }//GEN-LAST:event_jBtnChonKhach1ActionPerformed

    private void jBtnThemKhachActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThemKhachActionPerformed
    {//GEN-HEADEREND:event_jBtnThemKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThemKhachActionPerformed

    private void jBtnHuyKhachActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyKhachActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuyKhachActionPerformed

    private void jBtnXoaKhachActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaKhachActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKhachActionPerformed

    private void jTableKhachHangMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableKhachHangMouseClicked
    {//GEN-HEADEREND:event_jTableKhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableKhachHangMouseClicked

    private void jBtnChonTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonTourActionPerformed
    {//GEN-HEADEREND:event_jBtnChonTourActionPerformed
        // TODO add your handling code here:
        BangTour bangTour = new BangTour();
        bangTour.doanForm = this;
    }//GEN-LAST:event_jBtnChonTourActionPerformed

    public int getRowTour()
    {
        return rowTour;
    }

    public void setRowTour(int rowTour)
    {
        this.rowTour = rowTour;
    }

    public DefaultTableModel getTbModelTour()
    {
        return tbModelDoan;
    }

    public void setTbModelTour(DefaultTableModel tbModelTour)
    {
        this.tbModelDoan = tbModelTour;
    }

//    public JButton getjBtnCapPhatMaNV()
//    {
////        return jBtnCapPhatMaLH;
//    }
    public JButton getjBtnXoaNV()
    {
        return jBtnXemTour;
    }

    public JButton getjBtnRefresh()
    {
        return jBtnRefreshDoan;
    }

    public void setjBtnRefresh(JButton jBtnRefresh)
    {
        this.jBtnRefreshDoan = jBtnRefresh;
    }

    public JTabbedPane getjTabbedPane1()
    {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1)
    {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTextField getjTextTimKiemNV()
    {
        return jTextTimKiemDoan;
    }

    public void setjTextTimKiemNV(JTextField jTextTimKiemNV)
    {
        this.jTextTimKiemDoan = jTextTimKiemNV;
    }

    public JButton getjButtonTimKiem()
    {
        return jBtnTimKiemDoan;
    }

    public void setjButtonTimKiem(JButton jButtonTimKiem)
    {
        this.jBtnTimKiemDoan = jButtonTimKiem;
    }

    public JTextField getjTextMaDiaDiem()
    {
        return jTextMaNV;
    }

    public void setjTextMaDiaDiem(JTextField jTextMaDiaDiem)
    {
        this.jTextMaNV = jTextMaDiaDiem;
    }

    public JTextField getjTextTenDiaDiem()
    {
        return jTextTenNV;
    }

    public void setjTextTenDiaDiem(JTextField jTextTenDiaDiem)
    {
        this.jTextTenNV = jTextTenDiaDiem;
    }

    public String getMaDiaDiem()
    {
        return maDiaDiem;
    }

    public void setMaDiaDiem(String maDiaDiem)
    {
        this.maDiaDiem = maDiaDiem;
    }

    public String getTenDiaDiem()
    {
        return tenDiaDiem;
    }

    public void setTenDiaDiem(String TenDiaDiem)
    {
        this.tenDiaDiem = TenDiaDiem;
    }

    public JPanel getjPanel2()
    {
        return jPanelQLTour;
    }

    public void setjPanel2(JPanel jPanel2)
    {
        this.jPanelQLTour = jPanel2;
    }

    public JButton getjButtonExcel()
    {
        return jBtnThemTour;
    }

    public void setjButtonExcel(JButton jButtonExcel)
    {
        this.jBtnThemTour = jButtonExcel;
    }

    public JTextField getjTextGiaTour()
    {
        return jTextGiaTour;
    }

    public void setjTextGiaTour(JTextField jTextGiaTour)
    {
        this.jTextGiaTour = jTextGiaTour;
    }

    public JTextField getjTextLoaiHinh()
    {
        return jTextLoaiTour;
    }

    public void setjTextLoaiHinh(JTextField jTextLoaiHinh)
    {
        this.jTextLoaiTour = jTextLoaiHinh;
    }

    public String getMaTour()
    {
        return maTour;
    }

    public void setMaTour(String maTour)
    {
        this.maTour = maTour;
    }

    public String getMaLoai()
    {
        return maLoai;
    }

    public void setMaLoai(String maLoai)
    {
        this.maLoai = maLoai;
    }

    public String getMaGia()
    {
        return maGia;
    }

    public void setMaGia(String maGia)
    {
        this.maGia = maGia;
    }

    public String getMaGiaHienHanh()
    {
        return maGiaHienHanh;
    }

    public void setMaGiaHienHanh(String maGiaHienHanh)
    {
        this.maGiaHienHanh = maGiaHienHanh;
    }

    public String getMaLoaiHienHanh()
    {
        return maLoaiHienHanh;
    }

    public void setMaLoaiHienHanh(String maLoaiHienHanh)
    {
        this.maLoaiHienHanh = maLoaiHienHanh;
    }

    public String getTenTour()
    {
        return tenTour;
    }

    public void setTenTour(String tenTour)
    {
        this.tenTour = tenTour;
    }

    public JDateChooser getjDateNgayBD()
    {
        return jDateNgayBD;
    }

    public void setjDateNgayBD(JDateChooser jDateNgayBD)
    {
        this.jDateNgayBD = jDateNgayBD;
    }

    public JDateChooser getjDateNgayKT()
    {
        return jDateNgayKT;
    }

    public void setjDateNgayKT(JDateChooser jDateNgayKT)
    {
        this.jDateNgayKT = jDateNgayKT;
    }

    public JButton getjBtnThemDD()
    {
        return jBtnThemNV;
    }

    public void setjBtnThemDD(JButton jBtnThemDD)
    {
        this.jBtnThemNV = jBtnThemDD;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapPhatMaTour;
    private javax.swing.JButton jBtnChonChiPhi;
    private javax.swing.JButton jBtnChonKhach1;
    private javax.swing.JButton jBtnChonNV;
    private javax.swing.JButton jBtnChonTour;
    private javax.swing.JButton jBtnHuyKhach;
    private javax.swing.JButton jBtnHuyNV;
    private javax.swing.JButton jBtnHuyTour;
    private javax.swing.JButton jBtnRefreshDoan;
    private javax.swing.JButton jBtnSuaNV;
    private javax.swing.JButton jBtnSuaTour;
    private javax.swing.JButton jBtnThemKhach;
    private javax.swing.JButton jBtnThemNV;
    private javax.swing.JButton jBtnThemTour;
    private javax.swing.JButton jBtnTimKiemDoan;
    private javax.swing.JButton jBtnXemTour;
    private javax.swing.JButton jBtnXoaKhach;
    private javax.swing.JButton jBtnXoaNV;
    private javax.swing.JButton jBtnXoaTour;
    private com.toedter.calendar.JDateChooser jDateNgayBD;
    private com.toedter.calendar.JDateChooser jDateNgayKT;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbDiaDiem;
    private javax.swing.JLabel jLbDiaDiem1;
    private javax.swing.JLabel jLbManv;
    private javax.swing.JLabel jLbManv1;
    private javax.swing.JLabel jLbThuTu1;
    private javax.swing.JLabel jLbThuTu2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelChiTietTour;
    private javax.swing.JPanel jPanelKhachHang;
    private javax.swing.JPanel jPanelNhanVien;
    private javax.swing.JPanel jPanelQLTour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDoan;
    private javax.swing.JTable jTableKhachHang;
    private javax.swing.JTable jTableNhanVien;
    private javax.swing.JTextField jTextChiPhi;
    private javax.swing.JTextField jTextChiTiet;
    private javax.swing.JTextField jTextGiaTour;
    private javax.swing.JTextField jTextLoaiTour;
    private javax.swing.JTextField jTextMaKhach1;
    private javax.swing.JTextField jTextMaNV;
    private javax.swing.JTextField jTextMaTour1;
    private javax.swing.JTextField jTextMadoan;
    private javax.swing.JTextField jTextNhiemVu;
    private javax.swing.JTextField jTextSDT;
    private javax.swing.JTextField jTextTenDoan;
    private javax.swing.JTextField jTextTenKhach1;
    private javax.swing.JTextField jTextTenNV;
    private javax.swing.JTextField jTextTenTour1;
    private javax.swing.JTextField jTextTimKiemDoan;
    // End of variables declaration//GEN-END:variables
}
