/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import BUS.*;
//import DAO.XuatExcel;
//import DTO.ChucVuDTO;
//import DTO.CongViecDTO;
//import DTO.PhongBanDTO;
import BUS.GiaTourBUS;
import BUS.LoaiHinhTourBUS;
import BUS.TourBUS;
import DTO.DiaDiemThamQuanDTO;
import DTO.GiaTourDTO;
import DTO.LoaiHinhTourDTO;
import DTO.TourDTO;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyung
 */
public class TourForm extends javax.swing.JPanel {

    /**
     * Creates new form jPanel2
     */
    static int flagtkmk = 0;
    TourBUS tourBUS = new TourBUS();
    GiaTourBUS giaTourBUS = new GiaTourBUS();
    ChiTietTour chiTietTour = new ChiTietTour();
    LoaiHinhTourBUS loaiHinhTourBUS = new LoaiHinhTourBUS();
    public BufferedImage i = null;
    public String imgName = null;
    int rowTour,rowDiaDiemThamQuan,flagThemDiaDiem;
    private String maTour, tenTour, maLoai, maLoaiHienHanh, maGia, maGiaHienHanh, maTourChiTiet,tenTourChiTiet;
    private String maDiaDiem,tenDiaDiem,thuTu;
    private ArrayList<DiaDiemThamQuanDTO> diaDiemThamQuanTempArr;
    Vector tbColTour = new Vector();//Vector chứa các dòng dữ liệu của bảng.
    Vector tbColDiadiem = new Vector();//Vector chứa các tiêu đề của bảng.
    Vector tbColDoan = new Vector();
    DefaultTableModel tbModelTour, tbModelDiadiem, tbModelDoan;

    public TourForm() {
        initComponents();
        //initTableTour();
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonLoaiHinh.setEnabled(false);
        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
        jBtnThemDD.setEnabled(false);
        jBtnSuaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnChonDiaDiem.setEnabled(false);
    }

    public void reloadData() {
        tourBUS = new TourBUS();
        giaTourBUS = new GiaTourBUS();
        loaiHinhTourBUS = new LoaiHinhTourBUS();
    }

    public void initTableTour() {
        reloadData();
        tbModelTour.setRowCount(0);
        tableModelTour(tbModelTour);
        jTableTour.setModel(tbModelTour);
    }

    public void tableModelTour(DefaultTableModel model) {
        for (TourDTO tour : tourBUS.getTourDTOS()) {
            Vector row = new Vector();
            row.add(tour.getMaTour());
            row.add(tour.getTenTour());
            for (LoaiHinhTourDTO loaiHinhTour : loaiHinhTourBUS.getLoaiHinhTourDTOs()) {
                if (loaiHinhTour.getMaLoai().equals(tour.getMaLoai())) {
                    row.add(loaiHinhTour.getTenLoai());
                }
            }
            for (GiaTourDTO giaTour : giaTourBUS.getGiaTourDTOs()) {
                if (giaTour.getMaTour().equals(tour.getMaTour()) && giaTour.getHienHanh() == 1) {
                    row.add(giaTour.getThanhTien());
                    row.add(giaTour.getTgBatDau());
                    row.add(giaTour.getTgKetThuc());
                }
            }
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelQLTour = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jBtnChonGiaTour = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextGiaTour = new javax.swing.JTextField();
        jDateNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jTextTenTour = new javax.swing.JTextField();
        jTextLoaiHinh = new javax.swing.JTextField();
        jBtnChonLoaiHinh = new javax.swing.JButton();
        jDateNgayBD = new com.toedter.calendar.JDateChooser();
        jBtnCapPhatMaTour = new javax.swing.JButton();
        jTextMaTour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLbManv = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextDacDiem = new javax.swing.JTextField();
        jBtnThemTour = new javax.swing.JButton();
        jBtnXoaTour = new javax.swing.JButton();
        jBtnSuaTour = new javax.swing.JButton();
        jTextTimKiemTour = new javax.swing.JTextField();
        jBtnTimKiemTour = new javax.swing.JButton();
        jBtnRefreshTour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTour = new javax.swing.JTable();
        jBtnXemTour = new javax.swing.JButton();
        jBtnHuyTour = new javax.swing.JButton();
        jPanelChiTietTour = new javax.swing.JPanel();
        jTextTimKiemNV1 = new javax.swing.JTextField();
        jButtonTimKiem1 = new javax.swing.JButton();
        jBtnRefresh1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextMaTour1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextTenTour1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextTenDiaDiem = new javax.swing.JTextField();
        jTextMaDiaDiem = new javax.swing.JTextField();
        jBtnChonDiaDiem = new javax.swing.JButton();
        jLbDiaDiem = new javax.swing.JLabel();
        jBtnThemDD = new javax.swing.JButton();
        jBtnSuaDD = new javax.swing.JButton();
        jTextThuTu = new javax.swing.JTextField();
        jBtnLuuDD = new javax.swing.JButton();
        jBtnHuyDD = new javax.swing.JButton();
        jBtnXoaDD = new javax.swing.JButton();
        jLbThuTu1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDiadiem = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDoan = new javax.swing.JTable();
        jLbThuTu = new javax.swing.JLabel();
        jPanelTLTour = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextMaLoaiHinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextTenLoaiHinh = new javax.swing.JTextField();
        jBtnCapPhatMaLH = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 242, 249));
        setPreferredSize(new java.awt.Dimension(990, 650));

        jTabbedPane1.setBackground(new java.awt.Color(233, 242, 249));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelQLTour.setBackground(new java.awt.Color(233, 242, 249));

        jPanel4.setBackground(new java.awt.Color(233, 242, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Tour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("<html> <body>Ngày Kết Thúc<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 30));

        jBtnChonGiaTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonGiaTour.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonGiaTour.setText("...");
        jBtnChonGiaTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonGiaTour.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonGiaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonGiaTourActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnChonGiaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("<html> <body>Đặc Điểm<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jTextGiaTour.setBackground(new java.awt.Color(214, 217, 223));
        jTextGiaTour.setForeground(new java.awt.Color(51, 51, 51));
        jTextGiaTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jTextGiaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 160, 30));

        jDateNgayKT.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayKT.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateNgayKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 200, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("<html> <body>Tên Tour<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jTextTenTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenTourActionPerformed(evt);
            }
        });
        jPanel4.add(jTextTenTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 30));

        jTextLoaiHinh.setEditable(false);
        jTextLoaiHinh.setBackground(new java.awt.Color(214, 217, 223));
        jPanel4.add(jTextLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 30));

        jBtnChonLoaiHinh.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonLoaiHinh.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonLoaiHinh.setText("...");
        jBtnChonLoaiHinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonLoaiHinh.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonLoaiHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonLoaiHinhActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnChonLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jDateNgayBD.setBackground(new java.awt.Color(214, 217, 223));
        jDateNgayBD.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateNgayBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 200, 30));

        jBtnCapPhatMaTour.setBackground(new java.awt.Color(81, 113, 131));
        jBtnCapPhatMaTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_32.png"))); // NOI18N
        jBtnCapPhatMaTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCapPhatMaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapPhatMaTourActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnCapPhatMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 30, 30));

        jTextMaTour.setEditable(false);
        jTextMaTour.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaLoaiHinh.setEditable(false);
        jPanel4.add(jTextMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("<html> <body> Mã Tour <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("<html> <body>Ngày Bắt Đầu<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, 30));

        jLbManv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv.setText("<html> <body>Giá Tour<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setText("<html> <body>Loại Hình<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jTextDacDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDacDiemActionPerformed(evt);
            }
        });
        jPanel4.add(jTextDacDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, 70));

        jBtnThemTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThemTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThemTour.setText("Thêm");
        jBtnThemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemTourActionPerformed(evt);
            }
        });

        jBtnXoaTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoaTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoaTour.setText("Xóa");
        jBtnXoaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaTourActionPerformed(evt);
            }
        });

        jBtnSuaTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSuaTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSuaTour.setText("Sửa");
        jBtnSuaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaTourActionPerformed(evt);
            }
        });

        jBtnTimKiemTour.setText("Tìm kiếm");
        jBtnTimKiemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTimKiemTourActionPerformed(evt);
            }
        });

        jBtnRefreshTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefreshTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefreshTour.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefreshTour.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefreshTour.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefreshTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshTourActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTableTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTourMouseClicked(evt);
            }
        });
        tbColTour.add("Mă Tour");
        tbColTour.add("Tên Tour");
        tbColTour.add("Loại Hình");
        tbColTour.add("Giá Tour");
        tbColTour.add("Ngày Bắt Đầu");
        tbColTour.add("Ngày Kết Thúc");
        tbModelTour= new DefaultTableModel(tbColTour,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableTour.setModel (tbModelTour);
        jTableTour.setShowGrid(true);
        jTableTour.setFocusable(false);
        jTableTour.setIntercellSpacing(new Dimension(0,0));
        jTableTour.setRowHeight(25);
        jTableTour.getTableHeader().setOpaque(false);
        jTableTour.setFillsViewportHeight(true);
        jTableTour.getTableHeader().setBackground(new Color(232,57,99));
        jTableTour.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableTour.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableTour.setSelectionBackground(new Color(52,152,219));
        jScrollPane1.setViewportView(jTableTour);
        jTableTour.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        //jTable1.setModel (new DefaultTableModel(tableRow,tableCol));

        jBtnXemTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXemTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXemTour.setText("Xem");
        jBtnXemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXemTourActionPerformed(evt);
            }
        });

        jBtnHuyTour.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuyTour.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuyTour.setText("Hủy");
        jBtnHuyTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQLTourLayout = new javax.swing.GroupLayout(jPanelQLTour);
        jPanelQLTour.setLayout(jPanelQLTourLayout);
        jPanelQLTourLayout.setHorizontalGroup(
            jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(jTextTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefreshTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBtnXoaTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSuaTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnXemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelQLTourLayout.setVerticalGroup(
            jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnXemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelQLTourLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jBtnSuaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jBtnXoaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelQLTourLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnRefreshTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnTimKiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Quản lý Tour", jPanelQLTour);

        jPanelChiTietTour.setBackground(new java.awt.Color(233, 242, 249));

        jButtonTimKiem1.setText("Tìm kiếm");
        jButtonTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiem1ActionPerformed(evt);
            }
        });

        jBtnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_25px.png"))); // NOI18N
        jBtnRefresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRefresh1.setMaximumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh1.setMinimumSize(new java.awt.Dimension(50, 50));
        jBtnRefresh1.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefresh1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("<html> <body> Mã Tour <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");

        jTextMaTour1.setEditable(false);
        jTextMaTour1.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaLoaiHinh.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setText("<html> <body>Tên Tour<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");

        jTextTenTour1.setEditable(false);
        jTextTenTour1.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenTour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenTour1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(233, 242, 249));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Địa Điểm Tham Quan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("<html> <body>Mã Địa Điểm<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jTextTenDiaDiem.setEditable(false);
        jTextTenDiaDiem.setBackground(new java.awt.Color(214, 217, 223));
        jTextTenDiaDiem.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenDiaDiem.setRequestFocusEnabled(false);
        jPanel5.add(jTextTenDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 30));

        jTextMaDiaDiem.setEditable(false);
        jTextMaDiaDiem.setBackground(new java.awt.Color(214, 217, 223));
        jPanel5.add(jTextMaDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 30));

        jBtnChonDiaDiem.setBackground(new java.awt.Color(136, 193, 184));
        jBtnChonDiaDiem.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jBtnChonDiaDiem.setText("...");
        jBtnChonDiaDiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnChonDiaDiem.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtnChonDiaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChonDiaDiemActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnChonDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLbDiaDiem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbDiaDiem.setText("<html> <body>Tên Địa Điểm<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanel5.add(jLbDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jBtnThemDD.setBackground(new java.awt.Color(136, 193, 184));
        jBtnThemDD.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnThemDD.setText("Thêm");
        jBtnThemDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemDDActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnThemDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 40));

        jBtnSuaDD.setBackground(new java.awt.Color(136, 193, 184));
        jBtnSuaDD.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnSuaDD.setText("Sửa");
        jBtnSuaDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaDDActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnSuaDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 40));

        jTextThuTu.setForeground(new java.awt.Color(51, 51, 51));
        jTextThuTu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jTextThuTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        jBtnLuuDD.setBackground(new java.awt.Color(136, 193, 184));
        jBtnLuuDD.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnLuuDD.setText("Lưu Thứ Tự");
        jBtnLuuDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLuuDDActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnLuuDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 40));

        jBtnHuyDD.setBackground(new java.awt.Color(136, 193, 184));
        jBtnHuyDD.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnHuyDD.setText("Hủy");
        jBtnHuyDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyDDActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnHuyDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, 40));

        jBtnXoaDD.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXoaDD.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXoaDD.setText("Xóa");
        jBtnXoaDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaDDActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnXoaDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, 40));

        jLbThuTu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbThuTu1.setText("<html> <body>Thứ Tự<span style=\"color:rgb(234, 21, 21)\">*</span> </body> </html>");
        jPanel5.add(jLbThuTu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jTableDiadiem.setAutoCreateRowSorter(true);
        jTableDiadiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableDiadiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDiadiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDiadiemMouseClicked(evt);
            }
        });
        tbColDiadiem.add("Mă Địa Điểm");
        tbColDiadiem.add("Tên Địa Điểm");
        tbColDiadiem.add("Thứ Tự");
        tbModelDiadiem= new DefaultTableModel(tbColDiadiem,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableDiadiem.setModel (tbModelDiadiem);
        jTableDiadiem.setShowGrid(true);
        jTableDiadiem.setFocusable(false);
        jTableDiadiem.setIntercellSpacing(new Dimension(0,0));
        jTableDiadiem.setRowHeight(25);
        jTableDiadiem.getTableHeader().setOpaque(false);
        jTableDiadiem.setFillsViewportHeight(true);
        jTableDiadiem.getTableHeader().setBackground(new Color(232,57,99));
        jTableDiadiem.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableDiadiem.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableDiadiem.setSelectionBackground(new Color(52,152,219));
        jTableDiadiem.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTableDiadiem);

        jTableDoan.setAutoCreateRowSorter(true);
        jTableDoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDoanMouseClicked(evt);
            }
        });
        tbColDoan.add("Mă Đoàn");
        tbColDoan.add("Tên Ðoàn");
        tbColDoan.add("Giá Ðoàn");
        tbColDoan.add("Ngày Bắt Đầu");
        tbColDoan.add("Ngày Kết Thúc");
        tbColDoan.add("Số Người");
        tbModelDoan= new DefaultTableModel(tbColDoan,5){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableDoan.setModel (tbModelDoan);
        jTableDoan.setShowGrid(true);
        jTableDoan.setFocusable(false);
        jTableDoan.setIntercellSpacing(new Dimension(0,0));
        jTableDoan.setRowHeight(25);
        jTableDoan.getTableHeader().setOpaque(false);
        jTableDoan.setFillsViewportHeight(true);
        jTableDoan.getTableHeader().setBackground(new Color(232,57,99));
        jTableDoan.getTableHeader().setForeground(new Color(141, 22, 22));
        jTableDoan.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableDoan.setSelectionBackground(new Color(52,152,219));
        jTableDoan.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(jTableDoan);

        jLbThuTu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbThuTu.setText("<html><body>Danh Sách Đoàn Của Tour</body> </html>");

        javax.swing.GroupLayout jPanelChiTietTourLayout = new javax.swing.GroupLayout(jPanelChiTietTour);
        jPanelChiTietTour.setLayout(jPanelChiTietTourLayout);
        jPanelChiTietTourLayout.setHorizontalGroup(
            jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChiTietTourLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChiTietTourLayout.createSequentialGroup()
                        .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelChiTietTourLayout.createSequentialGroup()
                                .addComponent(jLbThuTu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTimKiemNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelChiTietTourLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMaTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTenTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChiTietTourLayout.setVerticalGroup(
            jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChiTietTourLayout.createSequentialGroup()
                .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelChiTietTourLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTenTour1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelChiTietTourLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanelChiTietTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTimKiemNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbThuTu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi tiết Tour", jPanelChiTietTour);

        jPanelTLTour.setBackground(new java.awt.Color(233, 242, 249));
        jPanelTLTour.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelTLTour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("<html> <body> Mã Loại Hình<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanelTLTour.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 30));

        jTextMaLoaiHinh.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaLoaiHinh.setEditable(false);
        jPanelTLTour.add(jTextMaLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 140, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("<html>  <body> Tên Loại Hình<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanelTLTour.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 30));
        jPanelTLTour.add(jTextTenLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 180, 30));

        jBtnCapPhatMaLH.setBackground(new java.awt.Color(81, 113, 131));
        jBtnCapPhatMaLH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_account_16.png"))); // NOI18N
        jBtnCapPhatMaLH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCapPhatMaLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapPhatMaLHActionPerformed(evt);
            }
        });
        jPanelTLTour.add(jBtnCapPhatMaLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 30, 30));

        jTabbedPane1.addTab("Loại hình Tour", jPanelTLTour);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String ktra() {
        /*String temp = "";
        if (jTextMaLoaiHinh.getText().equals("")) {
            temp += "Vui lòng cấp phát mã nhân viên!\n";
        }

        String hoten = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s]{5,32}$";
        if (!Pattern.matches(hoten, jTextHonv.getText())) {
            temp += "- Họ Nhân Viên không hợp lệ!\n";
        }

        String ten = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s]{2,32}$";
        if (!Pattern.matches(ten, jTextTenLoaiHinh.getText())) {
            temp += "- Tên Nhân Viên không hợp lệ!\n";
        }
        String ngaysinh = ((JTextField) jDateNgaySinh.getDateEditor().getUiComponent()).getText();
        String ngaycmnd = ((JTextField) jDateNgaycapcmnd.getDateEditor().getUiComponent()).getText();
        if (ngaysinh.equals("")) {
            temp += "- Ngày sinh không được để trống!\n";
        }
        if (ngaycmnd.equals("")) {
            temp += "- Ngày cấp CMND không được để trống!\n";
        }
        if (!ngaysinh.equals("") && !ngaycmnd.equals("")) {
            String[] arrNgaySinh = ngaysinh.split("-");
            String[] arrNgayCap = ngaycmnd.split("-");
            if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) < 14) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            } else if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) == 14 && Integer.parseInt(arrNgayCap[1]) - Integer.parseInt(arrNgaySinh[1]) < 0) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            } else if (Integer.parseInt(arrNgayCap[0]) - Integer.parseInt(arrNgaySinh[0]) == 14 && Integer.parseInt(arrNgayCap[1]) - Integer.parseInt(arrNgaySinh[1]) == 0 && Integer.parseInt(arrNgayCap[2]) - Integer.parseInt(arrNgaySinh[2]) < 0) {
                temp += "- Ngày Cấp CMND không hợp lệ!\n";
            }
        }

        String noisinh = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(noisinh, jTextNoiSinh.getText())) {
            temp += "- Nơi Sinh không hợp lệ!\n";
        }

        String trinhdo = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(trinhdo, jTextTdhv.getText())) {
            temp += "- Trình Độ Học Vấn không hợp lệ!\n";
        }

        String diachi = "^[(AÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶEÉÈẺẼẸÊẾỀỂỄỆIÍÌỈĨỊOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢUÚÙỦŨỤƯỨỪỬỮỰYÝỲỶỸỴĐaáàảãạâấầẩẫậăắằẳẵặeéèẻẽẹêếềểễệiíìỉĩịoóòỏõọôốồổỗộơớờởỡợuúùủũụưứừửữựyýỳỷỹỵđ|a-z|A-Z|\\s|/-|0-9]{3,100}$";
        if (!Pattern.matches(diachi, jTextDiaChi.getText())) {
            temp += "- Địa Chỉ không hợp lệ!\n";
        }

        String cmnd = "^\\d{12}$|^\\d{9}$";
        if (!Pattern.matches(cmnd, jTextCmnd.getText())) {
            temp += "- CMND không hợp lệ!\n";
        }

        String sdt = "^\\d{8}$|(^[0]+[1-9]\\d{8})$";
        if (!Pattern.matches(sdt, jTextSDT.getText())) {
            temp += "- Số Điện Thoại không hợp lệ!\n";
        }

        String gmail = "^[a-zA-z]+[a-zA-z0-9]+@+[azA-z0-9]+.+com$";
        if (!Pattern.matches(gmail, jTextEmail.getText())) {
            temp += "- Email không hợp lệ!\n";
        }
//        System.out.println(jDateNgaySinh.get());

        String luongcb = "([\\d]+.[\\d]+|[\\d]+)";
        if (!Pattern.matches(luongcb, jTextLuongcb.getText())) {
            temp += "- Lương Căn Bản không hợp lệ!\n";
        }*/
        return "";
    }

    private void jBtnCapPhatMaLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCapPhatMaLHActionPerformed
        // TODO add your handling code here:
//        String cpmanv = null;
//        cpmanv = tbnv.getDsnv().CapPhatManv();
//        tk.getjBtnThemNv().setEnabled(true);
//        jBtnHuy.setEnabled(true);
//        jTextManv.setText(cpmanv);
    }//GEN-LAST:event_jBtnCapPhatMaLHActionPerformed

    private void jBtnThemTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemTourActionPerformed
        // TODO add your handling code here:jBtnCapPhatMaTour.setEnabled(true);
        String maTour = (String) jTextMaTour.getText(),
                tenTour = (String) jTextTenTour.getText(),
                giaTour = (String) jTextGiaTour.getText(),
                ngayBD = (String) ((JTextField) jDateNgayBD.getDateEditor().getUiComponent()).getText(),
                ngayKT = (String) ((JTextField) jDateNgayKT.getDateEditor().getUiComponent()).getText();
        if (tourBUS.themTour(maTour, (String) getMaLoai(), tenTour,
                (String) jTextDacDiem.getText(), giaTour, ngayBD, ngayKT)) {
            Vector newrow = new Vector();
            newrow.add(maTour);
            newrow.add(tenTour);
            newrow.add((String) jTextLoaiHinh.getText());
            newrow.add(giaTour);
            newrow.add(ngayBD);
            newrow.add(ngayKT);
            tbModelTour.addRow(newrow);
            JOptionPane.showMessageDialog(this, "Thêm Tour thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMaTour.setText("");
        jTextTenTour.setText("");
        jTextLoaiHinh.setText("");
        jTextDacDiem.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonLoaiHinh.setEnabled(false);
        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnThemTourActionPerformed

    private void jBtnLuuDDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnLuuDDActionPerformed
    {//GEN-HEADEREND:event_jBtnLuuDDActionPerformed
        // TODO add your handling code here:
        jBtnChonDiaDiem.setEnabled(true);
        jBtnThemDD.setEnabled(true);
        jBtnSuaDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnLuuDDActionPerformed

    private void jBtnHuyDDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyDDActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyDDActionPerformed
        // TODO add your handling code here:
        jBtnChonDiaDiem.setEnabled(true);
        jBtnThemDD.setEnabled(false);
        jBtnSuaDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnHuyDDActionPerformed

    private void jButtonTimKiem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonTimKiem1ActionPerformed
    {//GEN-HEADEREND:event_jButtonTimKiem1ActionPerformed
        // TODO add your handling code here:
        tbModelDoan.setRowCount(0);
        String maDoan = jTextTimKiemNV1.getText();
        System.out.println(maDoan);
        chiTietTour.tbModelSearchDoanDuLich(tbModelDoan,maDoan);
    }//GEN-LAST:event_jButtonTimKiem1ActionPerformed

    private void jBtnRefresh1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnRefresh1ActionPerformed
    {//GEN-HEADEREND:event_jBtnRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRefresh1ActionPerformed

    private void jBtnRefreshTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnRefreshTourActionPerformed
    {//GEN-HEADEREND:event_jBtnRefreshTourActionPerformed
        //        // TODO add your handling code here:
        //        jTextTimKiemNV.setText("");
        //        tbnv.loadDataNV();
        //        tbModelTour.setRowCount(0);
        //        tbnv.bangnhanvien(tbModelTour);
        jTextTimKiemTour.setText("");
        initTableTour();
    }//GEN-LAST:event_jBtnRefreshTourActionPerformed

    private void jBtnTimKiemTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnTimKiemTourActionPerformed
    {//GEN-HEADEREND:event_jBtnTimKiemTourActionPerformed
        // TODO add your handling code here:
        //        String manv = jTextTimKiemNV.getText();
        //        tbnv.searchbangnhanvien(tbModelTour, manv);
        //        jTable1.setModel(tbModelTour);
        //        System.out.println("click tim kiem");
    }//GEN-LAST:event_jBtnTimKiemTourActionPerformed

    private void jBtnCapPhatMaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnCapPhatMaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnCapPhatMaTourActionPerformed
        // TODO add your handling code here:
        reloadData();
        String init = null;
        init = tourBUS.CapPhat(init);
        jTextMaTour.setText(init);
        jBtnCapPhatMaTour.setEnabled(false);
        jBtnThemTour.setEnabled(true);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(true);
        jBtnXemTour.setEnabled(false);
        jTextTenTour.setText("");
        jTextLoaiHinh.setText("");
        jTextDacDiem.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(true);
        jTextGiaTour.setBackground(new Color(255, 255, 255));
        jBtnChonLoaiHinh.setEnabled(true);
        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(true);
        jDateNgayKT.setEnabled(true);
    }//GEN-LAST:event_jBtnCapPhatMaTourActionPerformed

    private void jBtnChonGiaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonGiaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnChonGiaTourActionPerformed
        // TODO add your handling code here:
        BangGia bangGia = new BangGia(getMaTour(), getMaGiaHienHanh());
        bangGia.tourForm = this;
    }//GEN-LAST:event_jBtnChonGiaTourActionPerformed

    private void jBtnChonLoaiHinhActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonLoaiHinhActionPerformed
    {//GEN-HEADEREND:event_jBtnChonLoaiHinhActionPerformed
        // TODO add your handling code here:
        BangLoaiHinh bangLoaiHinh = new BangLoaiHinh();
        bangLoaiHinh.tourForm = this;
    }//GEN-LAST:event_jBtnChonLoaiHinhActionPerformed

    private void jBtnXoaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaTourActionPerformed
        // TODO add your handling code here:
        if (tourBUS.xoaTour(maTour)) {
            initTableTour();
            JOptionPane.showMessageDialog(this, "Xóa Tour thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMaTour.setText("");
        jTextTenTour.setText("");
        jTextLoaiHinh.setText("");
        jTextDacDiem.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonLoaiHinh.setEnabled(false);
        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnXoaTourActionPerformed

    private void jBtnSuaTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaTourActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaTourActionPerformed
        // TODO add your handling code here:
        String tenTour = (String) jTextTenTour.getText();
        System.out.println("Sua tour: " + maTour);
//                ngayBD = (String) ((JTextField)jDateNgayBD.getDateEditor().getUiComponent()).getText (),
//                ngayKT = (String) ((JTextField)jDateNgayKT.getDateEditor().getUiComponent()).getText ();
        if (tourBUS.suaTour(getMaTour(), tenTour, (String) jTextDacDiem.getText(), getMaLoaiHienHanh(), getMaLoai(), getMaGiaHienHanh(), getMaGia())) {
            initTableTour();
            JOptionPane.showMessageDialog(this, "Sửa Tour thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa Tour thất bại!");
        }
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMaTour.setText("");
        jTextTenTour.setText("");
        jTextLoaiHinh.setText("");
        jTextDacDiem.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonLoaiHinh.setEnabled(false);
        jBtnChonGiaTour.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnSuaTourActionPerformed

    private void jTableTourMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableTourMouseClicked
    {//GEN-HEADEREND:event_jTableTourMouseClicked
        if (evt.getSource() == jTableTour) {
            rowTour = jTableTour.getSelectedRow();
            if (rowTour != -1) {
                maTour = (String) jTableTour.getModel().getValueAt(rowTour, 0);
                tenTour = (String) jTableTour.getModel().getValueAt(rowTour, 1);
                if (!maTour.equals("null")) {
                    jTextMaTour.setText(maTour);
                    jTextTenTour.setText(tenTour);
                    jTextLoaiHinh.setText((String) jTableTour.getModel().getValueAt(rowTour, 2));
                    jTextGiaTour.setText((String) jTableTour.getModel().getValueAt(rowTour, 3));
                    try {
                        Date dateBD = new SimpleDateFormat("yyyy-MM-dd").parse(jTableTour.getModel().getValueAt(rowTour, 4).toString());
                        jDateNgayBD.setDate(dateBD);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(TourForm.this, e);
                        System.out.println("- Load sai ngày bắt đầu!");
                    }
                    try {
                        Date dateKT = new SimpleDateFormat("yyyy-MM-dd").parse(jTableTour.getModel().getValueAt(rowTour, 5).toString());
                        jDateNgayKT.setDate(dateKT);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(TourForm.this, e);
                        System.out.println("- Load sai ngày kết thúc!");
                    }
                    for (TourDTO tour : tourBUS.getTourDTOS()) {
                        if (maTour.equals(tour.getMaTour())) {
                            jTextDacDiem.setText(tour.getDacDiem());
                            setMaLoaiHienHanh(tour.getMaLoai());
                            setMaLoai(tour.getMaLoai());
                        }
                    }
                    setMaTour(maTour);
                    System.out.println("maTour: " + getMaTour());
                    System.out.println("maLoaiHH: " + getMaLoaiHienHanh());
                    for (GiaTourDTO giaTour : giaTourBUS.getGiaTourDTOs()) {
                        if (giaTour.getMaTour().equals(getMaTour()) && giaTour.getHienHanh() == 1) {
                            setMaGiaHienHanh(giaTour.getMaGia());
                            setMaGia(giaTour.getMaGia());
                        }
                    }
                    System.out.println("maGiaHH: " + getMaGiaHienHanh());
                    jBtnCapPhatMaTour.setEnabled(false);
                    jBtnThemTour.setEnabled(false);
                    jBtnSuaTour.setEnabled(true);
                    jBtnXoaTour.setEnabled(true);
                    jBtnHuyTour.setEnabled(true);
                    jBtnXemTour.setEnabled(true);
                    jTextGiaTour.setEditable(false);
                    jTextGiaTour.setBackground(new Color(214, 217, 223));
                    jBtnChonLoaiHinh.setEnabled(true);
                    jBtnChonGiaTour.setEnabled(true);
                    jDateNgayBD.setEnabled(false);
                    jDateNgayKT.setEnabled(false);
                } else {
                    jBtnCapPhatMaTour.setEnabled(true);
                    jBtnThemTour.setEnabled(false);
                    jBtnSuaTour.setEnabled(false);
                    jBtnXoaTour.setEnabled(false);
                    jBtnHuyTour.setEnabled(false);
                    jBtnXemTour.setEnabled(false);
                    jTextGiaTour.setEditable(false);
                    jTextGiaTour.setBackground(new Color(214, 217, 223));
                    jBtnChonLoaiHinh.setEnabled(false);
                    jBtnChonGiaTour.setEnabled(false);
                    jDateNgayBD.setEnabled(false);
                    jDateNgayKT.setEnabled(false);
                }
            }
        }

    }//GEN-LAST:event_jTableTourMouseClicked

    private void jTextTenTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenTourActionPerformed
    {//GEN-HEADEREND:event_jTextTenTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenTourActionPerformed

    private void jTextTenTour1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenTour1ActionPerformed
    {//GEN-HEADEREND:event_jTextTenTour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenTour1ActionPerformed

    private void jBtnChonDiaDiemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChonDiaDiemActionPerformed
    {//GEN-HEADEREND:event_jBtnChonDiaDiemActionPerformed
        // TODO add your handling code here:
        BangDiaDiem bangDiaDiem = new BangDiaDiem();
        bangDiaDiem.tourForm = this;
        bangDiaDiem.loadData();
    }//GEN-LAST:event_jBtnChonDiaDiemActionPerformed

    private void jBtnXoaDDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXoaDDActionPerformed
    {//GEN-HEADEREND:event_jBtnXoaDDActionPerformed
        // TODO add your handling code here:
        Vector row = new Vector();
        row.add(jTextMaDiaDiem.getText());
        row.add(jTextTenDiaDiem.getText());
        row.add(Integer.parseInt(jTextThuTu.getText()));
        if(chiTietTour.deleteDiaDiemThamQuan(maTourChiTiet,jTextMaDiaDiem.getText(),Integer.parseInt(jTextThuTu.getText()))){
            tbModelDiadiem.removeRow(rowDiaDiemThamQuan);
        }else{
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonDiaDiem.setEnabled(true);
        jBtnThemDD.setEnabled(false);
        jBtnSuaDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnXoaDDActionPerformed

    private void jBtnThemDDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnThemDDActionPerformed
    {//GEN-HEADEREND:event_jBtnThemDDActionPerformed
        // TODO add your handling code here:
        Vector row = new Vector();
        row.add(jTextMaDiaDiem.getText());
        row.add(jTextTenDiaDiem.getText());
        row.add(Integer.parseInt(jTextThuTu.getText()));
//        DiaDiemThamQuanDTO temp = new DiaDiemThamQuanDTO(jTextMaDiaDiem.getText(),maTourChiTiet,Integer.parseInt(jTextThuTu.getText()));
//        //System.out.println(jTextThuTu.getText());
//        int flag = 1;
//        for(DiaDiemThamQuanDTO a : chiTietTour.DiaDiemThamQuanDTOs()){
//            if(a.getMaDiaDiem().equals(jTextMaDiaDiem.getText())&&(a.getThuTu()==(Integer.parseInt(jTextThuTu.getText())))){
//                    flag=0;
//                    //System.out.println("Dup");
//                    break;
//                };
//            }
//        if(flag==1&&!jTextMaDiaDiem.getText().equals("")&&!jTextTenDiaDiem.getText().equals("")&&!jTextThuTu.getText().equals("")&&chiTietTour.checkDuplicateThuTu(maTourChiTiet,Integer.parseInt(jTextThuTu.getText()))){
//            tbModelDiadiem.addRow(row);
//            
//        }else {
//            System.out.println("Trùng hoặc rỗng");
//        }
        if(chiTietTour.addDiaDiemThamQuan(maTourChiTiet,jTextMaDiaDiem.getText(),Integer.parseInt(jTextThuTu.getText()))){
            tbModelDiadiem.addRow(row);
        }else{
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonDiaDiem.setEnabled(true);
        jBtnThemDD.setEnabled(false);
        jBtnSuaDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(false);
    }//GEN-LAST:event_jBtnThemDDActionPerformed

    private void jBtnSuaDDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSuaDDActionPerformed
    {//GEN-HEADEREND:event_jBtnSuaDDActionPerformed
        // TODO add your handling code here:
        //        int flag = 1;
//        if(diaDiemThamQuanTempArr.size()>0){
//            System.out.println("hello");
//            for(DiaDiemThamQuanDTO a : diaDiemThamQuanTempArr){
//                System.out.println(a.elementAt(2)+" "+jTextThuTu.getText());
//                if(a.elementAt(2).equals(jTextThuTu.getText())){
//                    flag=0;
//                    System.out.println();
//                    //break;
//                };
//            }
//        }
//        if(flag==1&&chiTietTour.checkDuplicateThuTu(maTourChiTiet,Integer.parseInt(jTextThuTu.getText()))){
//            if(diaDiemThamQuanTempArr.size()>0){
//                for(Vector a : diaDiemThamQuanTempArr){
//                    if(a.elementAt(0).equals(jTextMaDiaDiem.getText())&&a.elementAt(2).equals(tbModelDiadiem.getValueAt(rowDiaDiemThamQuan, 2))){
//                        a.setElementAt(jTextThuTu.getText(), 2);
//                        break;
//                    }
//                }
//            }
//            tbModelDiadiem.setValueAt(jTextThuTu.getText(), rowDiaDiemThamQuan, 2);
//   
        if(chiTietTour.updateDiaDiemThamQuan(maTourChiTiet,jTextMaDiaDiem.getText(),(int)tbModelDiadiem.getValueAt(rowDiaDiemThamQuan, 2),Integer.parseInt(jTextThuTu.getText()))){
            tbModelDiadiem.setValueAt(jTextThuTu.getText(), rowDiaDiemThamQuan, 2);
        }else{
            System.out.println("Loi them Dia Diem Tham Quan");
        }
        jBtnChonDiaDiem.setEnabled(true);
        if(flagThemDiaDiem==1){
            jBtnThemDD.setEnabled(true);
        }else
            jBtnThemDD.setEnabled(false);
        jBtnSuaDD.setEnabled(false);
        jBtnXoaDD.setEnabled(false);
        jBtnHuyDD.setEnabled(false);
        jBtnLuuDD.setEnabled(true);
    }//GEN-LAST:event_jBtnSuaDDActionPerformed

    private void jTableDiadiemMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableDiadiemMouseClicked
    {//GEN-HEADEREND:event_jTableDiadiemMouseClicked
        // TODO add your handling code here:
        rowDiaDiemThamQuan = jTableDiadiem.getSelectedRow();
        jTextMaDiaDiem.setText((String) jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 0));
        //System.out.println((String) jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 0));
        jTextTenDiaDiem.setText((String) jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 1));
        jTextThuTu.setText(Integer.toString((int) jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 2)));
        //System.out.println(Integer.toString( Integer.parseInt((String)jTableDiadiem.getValueAt(rowDiaDiemThamQuan, 2))));
        if (flagThemDiaDiem==1){ // NẾU TOUR CHƯA CÓ ĐOÀN
            jBtnChonDiaDiem.setEnabled(false);
            jBtnThemDD.setEnabled(false);
            jBtnSuaDD.setEnabled(true);
            jBtnXoaDD.setEnabled(true);
            jBtnHuyDD.setEnabled(true);
            jBtnLuuDD.setEnabled(false);
        } else { // NẾU CÓ ĐOÀN
            jBtnChonDiaDiem.setEnabled(false);
            jBtnThemDD.setEnabled(false);
            jBtnSuaDD.setEnabled(false);
            jBtnXoaDD.setEnabled(false);
            jBtnHuyDD.setEnabled(false);
            jBtnLuuDD.setEnabled(false);
        }
    }//GEN-LAST:event_jTableDiadiemMouseClicked

    private void jTableDoanMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableDoanMouseClicked
    {//GEN-HEADEREND:event_jTableDoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDoanMouseClicked

    private void jBtnXemTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXemTourActionPerformed
    {//GEN-HEADEREND:event_jBtnXemTourActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        rowTour = jTableTour.getSelectedRow();
        maTourChiTiet = (String) jTableTour.getModel().getValueAt(rowTour, 0);
        tenTourChiTiet = (String) jTableTour.getModel().getValueAt(rowTour, 1);
        jTextMaTour1.setText(maTourChiTiet);//System.out.println(maTourChiTiet);
        jTextTenTour1.setText(tenTour); System.out.println(tenTour);
        tbModelDoan.setRowCount(0);
        tbModelDiadiem.setRowCount(0);
        chiTietTour.tbModelDiaDiemThamQuan(tbModelDiadiem,maTourChiTiet);
        chiTietTour.tbModelDoanDuLich(tbModelDoan,maTourChiTiet);
        System.out.println(chiTietTour.countDoanTrongTour(maTourChiTiet));
        System.out.println(maTourChiTiet);
        if (chiTietTour.countDoanTrongTour(maTourChiTiet)==0){ // NẾU TOUR CHƯA CÓ ĐOÀN
            flagThemDiaDiem=1;
            jBtnChonDiaDiem.setEnabled(true);
            jBtnThemDD.setEnabled(false);
            jBtnSuaDD.setEnabled(false);
            jBtnXoaDD.setEnabled(false);
            jBtnHuyDD.setEnabled(false);
            jBtnLuuDD.setEnabled(false);
        } else { // NẾU CÓ ĐOÀN
            flagThemDiaDiem=0;
            jBtnChonDiaDiem.setEnabled(false);
            jBtnThemDD.setEnabled(false);
            jBtnSuaDD.setEnabled(false);
            jBtnXoaDD.setEnabled(false);
            jBtnHuyDD.setEnabled(false);
            jBtnLuuDD.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnXemTourActionPerformed

    private void jBtnHuyTourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnHuyTourActionPerformed
    {//GEN-HEADEREND:event_jBtnHuyTourActionPerformed
        // TODO add your handling code here:
        jBtnCapPhatMaTour.setEnabled(true);
        jBtnThemTour.setEnabled(false);
        jBtnSuaTour.setEnabled(false);
        jBtnXoaTour.setEnabled(false);
        jBtnHuyTour.setEnabled(false);
        jBtnXemTour.setEnabled(false);
        jTextMaTour.setText("");
        jTextTenTour.setText("");
        jTextLoaiHinh.setText("");
        jTextDacDiem.setText("");
        jTextGiaTour.setText("");
        jDateNgayBD.setCalendar(null);
        jDateNgayKT.setCalendar(null);
        jTextGiaTour.setEditable(false);
        jTextGiaTour.setBackground(new Color(214, 217, 223));
        jBtnChonGiaTour.setEnabled(false);
        jBtnChonLoaiHinh.setEnabled(false);
        jDateNgayBD.setEnabled(false);
        jDateNgayKT.setEnabled(false);
    }//GEN-LAST:event_jBtnHuyTourActionPerformed

    private void jTextDacDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDacDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDacDiemActionPerformed

//    DefaultTableModel md=tbnv.bangnhanvien ();
//    public void listPhongban(JComboBox cmb)
//    {
//        ArrayList<PhongBanDTO> cbdspb = tbpb.getDspb().getDspb().getDspb();
//        System.out.println("nhanvienForm " + tbpb.getDspb().getDspb().getDspb());
//        addCombo(cmb, cbdspb);
//    }
//    public void listChucvu(JComboBox cmb)
//    {
//        ArrayList<ChucVuDTO> cbdscvu = tbchucvu.getDscv().getDscv();
//        addCombo(cmb, cbdscvu);
//    }
//    public void listCongviec(JComboBox cmb)
//    {
//        ArrayList<CongViecDTO> cbdscviec = tbcviec.getDscviec().getDscviec();
//        addCombo(cmb, cbdscviec);
//    }
//
//    public void addCombo(JComboBox cmb, ArrayList list)
//    {
//        for (Object a : list)
//        {
//            cmb.addItem(a);
//        }
//    }
//    public JTable getjTable1()
//    {
////        return jTable1;
//    }
    public DefaultTableModel getModelnv() {
        return tbModelTour;
    }

//    public JButton getjBtnCapNhatNV()
//    {
//        return jBtnHuy1;
//    }
    public JButton getjBtnCapPhatMaNV() {
        return jBtnCapPhatMaLH;
    }

//    public JButton getjBtnHuy()
//    {
//        return jBtnHuy;
//    }
    public JButton getjBtnXoaNV() {
        return jBtnXemTour;
    }

//    public JButton getjBtnQuaylai()
//    {
//        return jBtnQuaylai;
//    }
//
//    public void setjBtnQuaylai(JButton jBtnQuaylai)
//    {
//        this.jBtnQuaylai = jBtnQuaylai;
//    }
    public JButton getjBtnRefresh() {
        return jBtnRefreshTour;
    }

    public void setjBtnRefresh(JButton jBtnRefresh) {
        this.jBtnRefreshTour = jBtnRefresh;
    }

//    public JButton getjBtnXacNhan()
//    {
//        return jBtnXacNhan;
//    }
//
//    public void setjBtnXacNhan(JButton jBtnXacNhan)
//    {
//        this.jBtnXacNhan = jBtnXacNhan;
//    }
    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTextField getjTextTimKiemNV() {
        return jTextTimKiemTour;
    }

    public void setjTextTimKiemNV(JTextField jTextTimKiemNV) {
        this.jTextTimKiemTour = jTextTimKiemNV;
    }

    public JButton getjButtonTimKiem() {
        return jBtnTimKiemTour;
    }

    public void setjButtonTimKiem(JButton jButtonTimKiem) {
        this.jBtnTimKiemTour = jButtonTimKiem;
    }
    
    public JTextField getjTextMaDiaDiem() {
        return jTextMaDiaDiem;
    }

    public void setjTextMaDiaDiem(JTextField jTextMaDiaDiem) {
        this.jTextMaDiaDiem = jTextMaDiaDiem;
    }

    public JTextField getjTextTenDiaDiem() {
        return jTextTenDiaDiem;
    }

    public void setjTextTenDiaDiem(JTextField jTextTenDiaDiem) {
        this.jTextTenDiaDiem = jTextTenDiaDiem;
    }
    
    public String getMaDiaDiem() {
        return maDiaDiem;
    }

    public void setMaDiaDiem(String maDiaDiem) {
        this.maDiaDiem = maDiaDiem;
    }

    public String getTenDiaDiem() {
        return tenDiaDiem;
    }

    public void setTenDiaDiem(String TenDiaDiem) {
        this.tenDiaDiem = TenDiaDiem;
    }

    public JPanel getjPanel2() {
        return jPanelQLTour;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanelQLTour = jPanel2;
    }

    public JButton getjButtonExcel() {
        return jBtnThemTour;
    }

    public void setjButtonExcel(JButton jButtonExcel) {
        this.jBtnThemTour = jButtonExcel;
    }

    public JTextField getjTextGiaTour() {
        return jTextGiaTour;
    }

    public void setjTextGiaTour(JTextField jTextGiaTour) {
        this.jTextGiaTour = jTextGiaTour;
    }

    public JTextField getjTextLoaiHinh() {
        return jTextLoaiHinh;
    }

    public void setjTextLoaiHinh(JTextField jTextLoaiHinh) {
        this.jTextLoaiHinh = jTextLoaiHinh;
    }

    public String getMaTour() {
        return maTour;
    }

    public void setMaTour(String maTour) {
        this.maTour = maTour;
    }

    public String getMaLoai() {
        return maLoai;
    }

    public void setMaLoai(String maLoai) {
        this.maLoai = maLoai;
    }

    public String getMaGia() {
        return maGia;
    }

    public void setMaGia(String maGia) {
        this.maGia = maGia;
    }

    public String getMaGiaHienHanh() {
        return maGiaHienHanh;
    }

    public void setMaGiaHienHanh(String maGiaHienHanh) {
        this.maGiaHienHanh = maGiaHienHanh;
    }

    public String getMaLoaiHienHanh() {
        return maLoaiHienHanh;
    }

    public void setMaLoaiHienHanh(String maLoaiHienHanh) {
        this.maLoaiHienHanh = maLoaiHienHanh;
    }

    public String getTenTour() {
        return tenTour;
    }

    public void setTenTour(String tenTour) {
        this.tenTour = tenTour;
    }

    public JDateChooser getjDateNgayBD() {
        return jDateNgayBD;
    }

    public void setjDateNgayBD(JDateChooser jDateNgayBD) {
        this.jDateNgayBD = jDateNgayBD;
    }

    public JDateChooser getjDateNgayKT() {
        return jDateNgayKT;
    }

    public void setjDateNgayKT(JDateChooser jDateNgayKT) {
        this.jDateNgayKT = jDateNgayKT;
    }

    public JButton getjBtnThemDD() {
        return jBtnThemDD;
    }

    public void setjBtnThemDD(JButton jBtnThemDD) {
        this.jBtnThemDD = jBtnThemDD;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapPhatMaLH;
    private javax.swing.JButton jBtnCapPhatMaTour;
    private javax.swing.JButton jBtnChonDiaDiem;
    private javax.swing.JButton jBtnChonGiaTour;
    private javax.swing.JButton jBtnChonLoaiHinh;
    private javax.swing.JButton jBtnHuyDD;
    private javax.swing.JButton jBtnHuyTour;
    private javax.swing.JButton jBtnLuuDD;
    private javax.swing.JButton jBtnRefresh1;
    private javax.swing.JButton jBtnRefreshTour;
    private javax.swing.JButton jBtnSuaDD;
    private javax.swing.JButton jBtnSuaTour;
    private javax.swing.JButton jBtnThemDD;
    private javax.swing.JButton jBtnThemTour;
    private javax.swing.JButton jBtnTimKiemTour;
    private javax.swing.JButton jBtnXemTour;
    private javax.swing.JButton jBtnXoaDD;
    private javax.swing.JButton jBtnXoaTour;
    private javax.swing.JButton jButtonTimKiem1;
    private com.toedter.calendar.JDateChooser jDateNgayBD;
    private com.toedter.calendar.JDateChooser jDateNgayKT;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbDiaDiem;
    private javax.swing.JLabel jLbManv;
    private javax.swing.JLabel jLbThuTu;
    private javax.swing.JLabel jLbThuTu1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelChiTietTour;
    private javax.swing.JPanel jPanelQLTour;
    private javax.swing.JPanel jPanelTLTour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDiadiem;
    private javax.swing.JTable jTableDoan;
    private javax.swing.JTable jTableTour;
    private javax.swing.JTextField jTextDacDiem;
    private javax.swing.JTextField jTextGiaTour;
    private javax.swing.JTextField jTextLoaiHinh;
    private javax.swing.JTextField jTextMaDiaDiem;
    private javax.swing.JTextField jTextMaLoaiHinh;
    private javax.swing.JTextField jTextMaTour;
    private javax.swing.JTextField jTextMaTour1;
    private javax.swing.JTextField jTextTenDiaDiem;
    private javax.swing.JTextField jTextTenLoaiHinh;
    private javax.swing.JTextField jTextTenTour;
    private javax.swing.JTextField jTextTenTour1;
    private javax.swing.JTextField jTextThuTu;
    private javax.swing.JTextField jTextTimKiemNV1;
    private javax.swing.JTextField jTextTimKiemTour;
    // End of variables declaration//GEN-END:variables
}
